DATA LIST FILE='C:\MICS6TUN\SPSS\MYCH.DAT' RECORDS=1
 /
 HH1         1-3   
 HH2         4-5   
 UF1         6-8   
 UF2         9-10  
 UFINT      11-13  
 UF3        14-15  
 LN         16-17  
 UF3N       18-97   (A)
 UF4N       98-177  (A)
 UF4       178-179 
 UF5       180-182 
 UF6       183-185 
 UF7D      186-187 
 UF7M      188-189 
 UF7Y      190-193 
 UF9       194-194 
 UF10      195-195 
 UF17      196-197 
 UF8H      198-199 
 UF8M      200-201 
 UF11H     202-203 
 UF11M     204-205 
 UF12      206-206 
 UF13      207-207 
 UF14      208-208 
 UF15      209-209 
 UFHINT    210-212 
 UB1D      213-214 
 UB1M      215-216 
 UB1Y      217-220 
 UB2       221-221 
 UB6       222-222 
 UB7       223-223 
 UB8       224-224 
 UB9       225-225 
 UB10A     226-229  (A)
 UB10D     230-233  (A)
 UB10E     234-237  (A)
 UB10F     238-241  (A)
 UB10X     242-245  (A)
 UB10NR    246-249  (A)
 BR1       250-250 
 BR2       251-251 
 BR3       252-252 
 EC1       253-254 
 EC2A      255-255 
 EC2B      256-256 
 EC2C      257-257 
 EC3A      258-258 
 EC3B      259-259 
 EC5AA     260-263  (A)
 EC5AB     264-267  (A)
 EC5AX     268-271  (A)
 EC5AY     272-275  (A)
 EC5ANR    276-279  (A)
 EC5BA     280-283  (A)
 EC5BB     284-287  (A)
 EC5BX     288-291  (A)
 EC5BY     292-295  (A)
 EC5BNR    296-299  (A)
 EC5CA     300-303  (A)
 EC5CB     304-307  (A)
 EC5CX     308-311  (A)
 EC5CY     312-315  (A)
 EC5CNR    316-319  (A)
 EC5DA     320-323  (A)
 EC5DB     324-327  (A)
 EC5DX     328-331  (A)
 EC5DY     332-335  (A)
 EC5DNR    336-339  (A)
 EC5EA     340-343  (A)
 EC5EB     344-347  (A)
 EC5EX     348-351  (A)
 EC5EY     352-355  (A)
 EC5ENR    356-359  (A)
 EC5FA     360-363  (A)
 EC5FB     364-367  (A)
 EC5FX     368-371  (A)
 EC5FY     372-375  (A)
 EC5FNR    376-379  (A)
 EC6       380-380 
 EC7       381-381 
 EC8       382-382 
 EC9       383-383 
 EC10      384-384 
 EC11      385-385 
 EC12      386-386 
 EC13      387-387 
 EC14      388-388 
 EC15      389-389 
 UCD2A     390-390 
 UCD2B     391-391 
 UCD2C     392-392 
 UCD2D     393-393 
 UCD2E     394-394 
 UCD2F     395-395 
 UCD2G     396-396 
 UCD2H     397-397 
 UCD2I     398-398 
 UCD2J     399-399 
 UCD2K     400-400 
 UCD4      401-401 
 UCD5      402-402 
 UCF2      403-403 
 UCF3      404-404 
 UCF4      405-405 
 UCF7      406-406 
 UCF9      407-407 
 UCF11     408-408 
 UCF12     409-409 
 UCF13     410-410 
 UCF14     411-411 
 UCF15     412-412 
 UCF16     413-413 
 UCF17     414-414 
 UCF18     415-415 
 UCF19     416-416 
 BD2       417-417 
 BD3       418-418 
 BD4       419-419 
 BD5       420-420 
 BD6       421-421 
 BD7A      422-422 
 BD7B      423-423 
 BD7C      424-424 
 BD7D      425-425 
 BD7D1     426-426 
 BD7E      427-427 
 BD7E1     428-428 
 BD7X      429-429 
 BD8A      430-430 
 BD8A1     431-431 
 BD8B      432-432 
 BD8C      433-433 
 BD8D      434-434 
 BD8E      435-435 
 BD8F      436-436 
 BD8G      437-437 
 BD8H      438-438 
 BD8I      439-439 
 BD8J      440-440 
 BD8K      441-441 
 BD8L      442-442 
 BD8M      443-443 
 BD8N      444-444 
 BD8X      445-445 
 BD9       446-446 
 BD8DUMMY  447-447 
 IM2       448-448 
 IM3       449-449 
 IM4A      450-450 
 IM4B      451-451 
 IM5       452-452 
 IM6BD     453-454 
 IM6BM     455-456 
 IM6BY     457-460 
 IM6H0D    461-462 
 IM6H0M    463-464 
 IM6H0Y    465-468 
 IM6VPO1D  469-470 
 IM6VPO1M  471-472 
 IM6VPO1Y  473-476 
 IM6VPO2D  477-478 
 IM6VPO2M  479-480 
 IM6VPO2Y  481-484 
 IM6VPO3D  485-486 
 IM6VPO3M  487-488 
 IM6VPO3Y  489-492 
 IM6VPI1D  493-494 
 IM6VPI1M  495-496 
 IM6VPI1Y  497-500 
 IM6VPI2D  501-502 
 IM6VPI2M  503-504 
 IM6VPI2Y  505-508 
 IM6PENTA1D  509-510 
 IM6PENTA1M  511-512 
 IM6PENTA1Y  513-516 
 IM6PENTA2D  517-518 
 IM6PENTA2M  519-520 
 IM6PENTA2Y  521-524 
 IM6PENTA3D  525-526 
 IM6PENTA3M  527-528 
 IM6PENTA3Y  529-532 
 IM6RR1D   533-534 
 IM6RR1M   535-536 
 IM6RR1Y   537-540 
 IM6RR2D   541-542 
 IM6RR2M   543-544 
 IM6RR2Y   545-548 
 IM6DTCPRD  549-550 
 IM6DTCPRM  551-552 
 IM6DTCPRY  553-556 
 IM6INFHEXA1D  557-558 
 IM6INFHEXA1M  559-560 
 IM6INFHEXA1Y  561-564 
 IM6INFHEXA2D  565-566 
 IM6INFHEXA2M  567-568 
 IM6INFHEXA2Y  569-572 
 IM6INFHEXA3D  573-574 
 IM6INFHEXA3M  575-576 
 IM6INFHEXA3Y  577-580 
 IM6PENTAXIM1D  581-582 
 IM6PENTAXIM1M  583-584 
 IM6PENTAXIM1Y  585-588 
 IM6PENTAXIM2D  589-590 
 IM6PENTAXIM2M  591-592 
 IM6PENTAXIM2Y  593-596 
 IM6PENTAXIM3D  597-598 
 IM6PENTAXIM3M  599-600 
 IM6PENTAXIM3Y  601-604 
 IM6HEPB1D  605-606 
 IM6HEPB1M  607-608 
 IM6HEPB1Y  609-612 
 IM6HEPB2D  613-614 
 IM6HEPB2M  615-616 
 IM6HEPB2Y  617-620 
 IM6HEPB3D  621-622 
 IM6HEPB3M  623-624 
 IM6HEPB3Y  625-628 
 IM6RTETRAPENTAD  629-630 
 IM6RTETRAPENTAM  631-632 
 IM6RTETRAPENTAY  633-636 
 IM6PREVSYN1D  637-638 
 IM6PREVSYN1M  639-640 
 IM6PREVSYN1Y  641-644 
 IM6PREVSYN2D  645-646 
 IM6PREVSYN2M  647-648 
 IM6PREVSYN2Y  649-652 
 IM6PREVSYN3D  653-654 
 IM6PREVSYN3M  655-656 
 IM6PREVSYN3Y  657-660 
 IM6PREVSYN4D  661-662 
 IM6PREVSYN4M  663-664 
 IM6PREVSYN4Y  665-668 
 IM6ROTARIX1D  669-670 
 IM6ROTARIX1M  671-672 
 IM6ROTARIX1Y  673-676 
 IM6ROTARIX2D  677-678 
 IM6ROTARIX2M  679-680 
 IM6ROTARIX2Y  681-684 
 IM6ROR1D  685-686 
 IM6ROR1M  687-688 
 IM6ROR1Y  689-692 
 IM6ROR2D  693-694 
 IM6ROR2M  695-696 
 IM6ROR2Y  697-700 
 IM6HAVRIX1D  701-702 
 IM6HAVRIX1M  703-704 
 IM6HAVRIX1Y  705-708 
 IM6HAVRIX2D  709-710 
 IM6HAVRIX2M  711-712 
 IM6HAVRIX2Y  713-716 
 IM9       717-717 
 IM11      718-718 
 IM14      719-719 
 IM15      720-720 
 IM16      721-721 
 IM18      722-722 
 IM19      723-723 
 IM19A     724-724 
 IM20      725-725 
 IM21      726-726 
 IM26      727-727 
 IM26A     728-728 
 IMPP9     729-729 
 IMPP11    730-730 
 IMPP14    731-731 
 IMPP15    732-732 
 IMPP16    733-733 
 IMPP18    734-734 
 IMPP19    735-735 
 IMPP19A   736-736 
 IMPP20A   737-737 
 IMPP20C   738-738 
 IMPP20B   739-739 
 IMPP21A   740-740 
 IMPP21B   741-741 
 IMPP21C   742-742 
 IMPP22    743-743 
 IMPP23    744-744 
 IMPP24    745-745 
 IMPP25    746-746 
 IMPP26    747-747 
 IMPP26A   748-748 
 IMPP29    749-749 
 IMPP29A   750-750 
 IMP9      751-751 
 IMP11     752-752 
 IMP14     753-753 
 IMP20B    754-754 
 IMP21B    755-755 
 IMP20C    756-756 
 IMP21C    757-757 
 IMP22     758-758 
 IMP23     759-759 
 IMP24     760-760 
 IMP25     761-761 
 IMP26     762-762 
 IMP26A    763-763 
 IMP29     764-764 
 IMP29A    765-765 
 CA1       766-766 
 CA3       767-767 
 CA4       768-768 
 CA5       769-769 
 CA6A      770-773  (A)
 CA6B      774-777  (A)
 CA6E      778-781  (A)
 CA6H      782-785  (A)
 CA6I      786-789  (A)
 CA6J      790-793  (A)
 CA6K      794-797  (A)
 CA6O      798-801  (A)
 CA6P      802-805  (A)
 CA6Q      806-809  (A)
 CA6R      810-813  (A)
 CA6X      814-817  (A)
 CA6NR     818-821  (A)
 CA7A      822-822 
 CA7B      823-823 
 CA7C      824-824 
 CA7D      825-825 
 CA9A      826-829  (A)
 CA9B      830-833  (A)
 CA9E      834-837  (A)
 CA9H      838-841  (A)
 CA9I      842-845  (A)
 CA9J      846-849  (A)
 CA9K      850-853  (A)
 CA9O      854-857  (A)
 CA9P      858-861  (A)
 CA9Q      862-865  (A)
 CA9R      866-869  (A)
 CA9X      870-873  (A)
 CA9Z      874-877  (A)
 CA9NR     878-881  (A)
 CA11A     882-885  (A)
 CA11B     886-889  (A)
 CA11E     890-893  (A)
 CA11H     894-897  (A)
 CA11I     898-901  (A)
 CA11J     902-905  (A)
 CA11K     906-909  (A)
 CA11O     910-913  (A)
 CA11P     914-917  (A)
 CA11Q     918-921  (A)
 CA11R     922-925  (A)
 CA11X     926-929  (A)
 CA11Z     930-933  (A)
 CA11NR    934-937  (A)
 CA12      938-938 
 CA13A     939-942  (A)
 CA13B     943-946  (A)
 CA13G     947-950  (A)
 CA13H     951-954  (A)
 CA13L     955-958  (A)
 CA13M     959-962  (A)
 CA13N     963-966  (A)
 CA13O     967-970  (A)
 CA13Q     971-974  (A)
 CA13X     975-978  (A)
 CA13NR    979-982  (A)
 CA14      983-983 
 CA16      984-984 
 CA17      985-985 
 CA18      986-986 
 CA20      987-987 
 CA21A     988-991  (A)
 CA21B     992-995  (A)
 CA21E     996-999  (A)
 CA21H    1000-1003 (A)
 CA21I    1004-1007 (A)
 CA21J    1008-1011 (A)
 CA21K    1012-1015 (A)
 CA21O    1016-1019 (A)
 CA21P    1020-1023 (A)
 CA21Q    1024-1027 (A)
 CA21R    1028-1031 (A)
 CA21X    1032-1035 (A)
 CA21NR   1036-1039 (A)
 CA22     1040-1040
 CA23L    1041-1044 (A)
 CA23M    1045-1048 (A)
 CA23N    1049-1052 (A)
 CA23O    1053-1056 (A)
 CA23R    1057-1060 (A)
 CA23S    1061-1064 (A)
 CA23T    1065-1068 (A)
 CA23X    1069-1072 (A)
 CA23Z    1073-1076 (A)
 CA23NR   1077-1080 (A)
 CA25A    1081-1084 (A)
 CA25B    1085-1088 (A)
 CA25E    1089-1092 (A)
 CA25H    1093-1096 (A)
 CA25I    1097-1100 (A)
 CA25J    1101-1104 (A)
 CA25K    1105-1108 (A)
 CA25O    1109-1112 (A)
 CA25P    1113-1116 (A)
 CA25Q    1117-1120 (A)
 CA25R    1121-1124 (A)
 CA25X    1125-1128 (A)
 CA25Z    1129-1132 (A)
 CA25NR   1133-1136 (A)
 CA31     1137-1138
 AN1      1139-1141
 AN2      1142-1143
 AN3N     1144-1223 (A)
 AN3      1224-1225
 AN4      1226-1226
 AN5N     1227-1306 (A)
 AN5      1307-1308
 AN6      1309-1311
 AN7N     1312-1391 (A)
 AN7      1392-1394
 AN8      1395-1398 (1)
 AN9      1399-1399
 AN11     1400-1404 (1)
 AN12     1405-1405
 AN13D    1406-1407
 AN13M    1408-1409
 AN13Y    1410-1413
 HH4      1414-1416
 HH6      1417-1417
 HH7      1418-1418
 HL4      1419-1419
 ED5A     1420-1420
 ED5B     1421-1422
 CDOI     1423-1426
 CDOB     1427-1430
 CAGE     1431-1432
 CAGE_6   1433-1433
 CAGE_11  1434-1434
 CAGED    1435-1438
 HAP      1439-1442 (1)
 HAZ      1443-1447 (2)
 HAM      1448-1452 (1)
 WAP      1453-1456 (1)
 WAZ      1457-1461 (2)
 WAM      1462-1466 (1)
 WHP      1467-1470 (1)
 WHZ      1471-1475 (2)
 WHM      1476-1480 (1)
 FLAG     1481-1481
 BMI      1482-1486 (2)
 ZBMI     1487-1491 (2)
 HAZ2     1492-1496 (2)
 WAZ2     1497-1501 (2)
 WHZ2     1502-1506 (2)
 HAZFLAG  1507-1507
 WAZFLAG  1508-1508
 WHZFLAG  1509-1509
 BMIFLAG  1510-1510
 WHZNOAGE 1511-1511
.
VARIABLE LABELS
  HH1      "Cluster number"
 /HH2      "Household number"
 /UF1      "Cluster number"
 /UF2      "Household number"
 /UFINT    "Interviewer number"
 /UF3      "Child's line number"
 /LN       "Line number"
 /UF3N     "Child's name"
 /UF4N     "Mother / Caretaker's name"
 /UF4      "Mother / Caretaker's line number"
 /UF5      "Interviewer number"
 /UF6      "Supervisor's number"
 /UF7D     "Day of interview"
 /UF7M     "Month of interview"
 /UF7Y     "Year of interview"
 /UF9      "Household interviewer"
 /UF10     "Consent"
 /UF17     "Result of interview for children under 5"
 /UF8H     "Start of interview - Hour"
 /UF8M     "Start of interview - Minutes"
 /UF11H    "End of interview - Hour"
 /UF11M    "End of interview - Minutes"
 /UF12     "Language of the questionnaire"
 /UF13     "Language of the interview"
 /UF14     "Native language of the respondent"
 /UF15     "Translator used"
 /UFHINT   "Household interviewer"
 /UB1D     "Day of birth of child"
 /UB1M     "Month of birth of child"
 /UB1Y     "Year of birth of child"
 /UB2      "Age of child"
 /UB6      "Ever attended early childhood education programme"
 /UB7      "Attended early childhood education programme anytime since the beginning of current school year"
 /UB8      "Currently attending early childhood education programme"
 /UB9      "Covered by any health insurance"
 /UB10A    "Health insurance - Mutual-health organization / Community-based health insurance"
 /UB10D    "Health insurance - Other privately purchased commercial health insurance"
 /UB10E    "Health insurance - Health insurance through employer"
 /UB10F    "Health insurance - Social security"
 /UB10X    "Health insurance - Other"
 /UB10NR   "Health insurance - No response"
 /BR1      "Birth certificate"
 /BR2      "Birth registered"
 /BR3      "Know how to register birth"
 /EC1      "Number of children's books or picture books for child"
 /EC2A     "Homemade toys"
 /EC2B     "Toys from shops"
 /EC2C     "Household objects or outside objects"
 /EC3A     "Days left alone for more than one hour"
 /EC3B     "Days left in the care of another child, that is someone less than 10 years old, for more than one hour"
 /EC5AA    "Read books - Mother"
 /EC5AB    "Read books - Father"
 /EC5AX    "Read books - Other"
 /EC5AY    "Read books - No one"
 /EC5ANR   "Read books - No response"
 /EC5BA    "Tell stories - Mother"
 /EC5BB    "Tell stories - Father"
 /EC5BX    "Tell stories - Other"
 /EC5BY    "Tell stories - No one"
 /EC5BNR   "Tell stories - No response"
 /EC5CA    "Sang songs - Mother"
 /EC5CB    "Sang songs - Father"
 /EC5CX    "Sang songs - Other"
 /EC5CY    "Sang songs - No one"
 /EC5CNR   "Sang songs - No response"
 /EC5DA    "Took outside - Mother"
 /EC5DB    "Took outside - Father"
 /EC5DX    "Took outside - Other"
 /EC5DY    "Took outside - No one"
 /EC5DNR   "Took outside - No response"
 /EC5EA    "Played with - Mother"
 /EC5EB    "Played with - Father"
 /EC5EX    "Played with - Other"
 /EC5EY    "Played with - No one"
 /EC5ENR   "Played with - No response"
 /EC5FA    "Named/counted - Mother"
 /EC5FB    "Named/counted - Father"
 /EC5FX    "Named/counted - Other"
 /EC5FY    "Named/counted - No one"
 /EC5FNR   "Named/counted - No response"
 /EC6      "Child identifies at least ten letters of the alphabet"
 /EC7      "Child reads at least four simple, popular words"
 /EC8      "Child knows name and recognizes symbol of all numbers from 1-10"
 /EC9      "Child able to pick up small object with 2 fingers"
 /EC10     "Child sometimes too sick to play"
 /EC11     "Child follows simple directions"
 /EC12     "Child able to do something independently"
 /EC13     "Child gets along well with other children"
 /EC14     "Child kicks, bites or hits other children or adults"
 /EC15     "Child gets distracted easily"
 /UCD2A    "Took away privileges"
 /UCD2B    "Explained why behaviour was wrong"
 /UCD2C    "Shook child"
 /UCD2D    "Shouted, yelled or screamed at child"
 /UCD2E    "Gave child something else to do"
 /UCD2F    "Spanked, hit or slapped child on bottom with bare hand"
 /UCD2G    "Hit child on the bottom or elsewhere with belt, brush, stick, etc."
 /UCD2H    "Called child dumb, lazy or another name"
 /UCD2I    "Hit or slapped child on the face, head or ears"
 /UCD2J    "Hit or slapped child on the hand, arm or leg"
 /UCD2K    "Beat child up as hard as one could"
 /UCD4     "Did answer to UCD5 for another children"
 /UCD5     "Child needs to be physically punished to be brought up properly"
 /UCF2     "Child wear glasses"
 /UCF3     "Child uses hearing aid"
 /UCF4     "Child uses any equipment or receive assistance for walking"
 /UCF7     "Child has difficulty seeing"
 /UCF9     "Child has difficulty hearing sounds like people voices or music"
 /UCF11    "Without using equipment or assistance child has difficulty walking"
 /UCF12    "When using equipment or assistance child has difficulty walking"
 /UCF13    "Compared with children of the same age, child has difficulty walking"
 /UCF14    "Compared with children of the same age, child has difficulty picking upsmall objects with his/her hand"
 /UCF15    "Child has difficulty understanding parent/caretaker"
 /UCF16    "Child has difficulty being understood by parent/caretaker when speaks"
 /UCF17    "Compared with children of the same age, child has difficulty learning things"
 /UCF18    "Compared with children of the same age, child has difficulty playing"
 /UCF19    "Compared with children of the same age, how much child kick, bite or hit other children or adults"
 /BD2      "Child ever been breastfed"
 /BD3      "Child still being breastfed"
 /BD4      "Child drank anything from a bottle with a nipple yesterday"
 /BD5      "Child drank ORS yesterday"
 /BD6      "Child drank or ate vitamin or mineral supplements yesterday"
 /BD7A     "Child drank plain water yesterday"
 /BD7B     "Child drank juice or juice drinks yesterday"
 /BD7C     "Child drank clear broth / watery soup yesterday"
 /BD7D     "Child drank infant formula yesterday"
 /BD7D1    "Times child drank infant formula"
 /BD7E     "Child drank milk yesterday"
 /BD7E1    "Times child drank milk"
 /BD7X     "Child drank any other liquid yesterday"
 /BD8A     "Child drank or ate yogurt yesterday"
 /BD8A1    "Times drank or ate yogurt"
 /BD8B     "Child ate fortified baby food (gerber, hero, cerelac, nestum, etc.) yesterday"
 /BD8C     "Child ate foods made from grains yesterday"
 /BD8D     "Child ate pumpkin, carrots, squash etc. yesterday"
 /BD8E     "Child ate white potatoes, white yams, manioc, cassava etc. yesterday"
 /BD8F     "Child ate green leafy vegetables yesterday"
 /BD8G     "Child ate ripe mangoes, papayas yesterday"
 /BD8H     "Child ate other fruits or vegetables yesterday"
 /BD8I     "Child ate liver, kidney, heart or other organ meat yesterday"
 /BD8J     "Child ate meat, such as beef, pork, lamb, goat, chicken, duck yesterday"
 /BD8K     "Child ate eggs yesterday"
 /BD8L     "Child ate fresh or dried fish or shellfish yesterday"
 /BD8M     "Child ate beans, peas, lentils or nuts or any food made from these yesterday"
 /BD8N     "Child ate cheese or other food made from milk yesterday"
 /BD8X     "Child ate other solid, semi-solid or soft food yesterday"
 /BD9      "Times child ate solid or semi-solid food"
 /BD8DUMMY "Dummy for BD8 explanation"
 /IM2      "Vaccination card for child"
 /IM3      "Ever had vaccination card"
 /IM4A     "Vaccination Location"
 /IM4B     "Vaccination Location"
 /IM5      "Card - document seen"
 /IM6BD    "Day of BCG immunization"
 /IM6BM    "Month of BCG immunization"
 /IM6BY    "Year of BCG immunization"
 /IM6H0D   "Day of HepB (at birth) immunization"
 /IM6H0M   "Month of HepB (at birth) immunization"
 /IM6H0Y   "Year of HepB (at birth) immunization"
 /IM6VPO1D "Day of VPO1immunization"
 /IM6VPO1M "Month of VPO1 immunization"
 /IM6VPO1Y "Year of VPO1 immunization"
 /IM6VPO2D "Day of VPO2 immunization"
 /IM6VPO2M "Month of VPO2 immunization"
 /IM6VPO2Y "Year of VPO2 immunization"
 /IM6VPO3D "Day of VPO3 immunization"
 /IM6VPO3M "Month of VPO3 immunization"
 /IM6VPO3Y "Year of VPO3 immunization"
 /IM6VPI1D "Day of VPI1 immunization"
 /IM6VPI1M "Month of VPI1 immunization"
 /IM6VPI1Y "Year of VPI1 immunization"
 /IM6VPI2D "Day of VPI2 immunization"
 /IM6VPI2M "Month of VPI2 immunization"
 /IM6VPI2Y "Year of VPI2 immunization"
 /IM6PENTA1D "Day of Pentavalent (DPTHibHepB) 1 immunization"
 /IM6PENTA1M "Month of Pentavalent (DPTHibHepB) 1 immunization"
 /IM6PENTA1Y "Year of Pentavalent (DPTHibHepB) 1 immunization"
 /IM6PENTA2D "Day of Pentavalent (DPTHibHepB) 2 immunization"
 /IM6PENTA2M "Month of Pentavalent (DPTHibHepB) 2 immunization"
 /IM6PENTA2Y "Year of Pentavalent (DPTHibHepB) 2 immunization"
 /IM6PENTA3D "Day of Pentavalent (DPTHibHepB) 3 immunization"
 /IM6PENTA3M "Month of Pentavalent (DPTHibHepB) 3 immunization"
 /IM6PENTA3Y "Year of Pentavalent (DPTHibHepB) 3 immunization"
 /IM6RR1D  "Day of Roougeole Rubeole 1 immunization"
 /IM6RR1M  "Month of Roougeole Rubeole 1 immunization"
 /IM6RR1Y  "Year of Roougeole Rubeole 1 immunization"
 /IM6RR2D  "Day of Roougeole Rubeole 2 immunization"
 /IM6RR2M  "Month of Roougeole Rubeole 2 immunization"
 /IM6RR2Y  "Year of Roougeole Rubeole 2 immunization"
 /IM6DTCPRD "Day of DTCPR immunization"
 /IM6DTCPRM "Month of DTCPR immunization"
 /IM6DTCPRY "Year of DTCPR immunization"
 /IM6INFHEXA1D "Day of Infarix Hexa 1 immunization"
 /IM6INFHEXA1M "Month of Infarix Hexa 1 immunization"
 /IM6INFHEXA1Y "Year of Infarix Hexa 1 immunization"
 /IM6INFHEXA2D "Day of Infarix Hexa 2 immunization"
 /IM6INFHEXA2M "Month of Infarix Hexa 2 immunization"
 /IM6INFHEXA2Y "Year of Infarix Hexa 2 immunization"
 /IM6INFHEXA3D "Day of Infarix Hexa 3 immunization"
 /IM6INFHEXA3M "Month of Infarix Hexa 3 immunization"
 /IM6INFHEXA3Y "Year of Infarix Hexa 3 immunization"
 /IM6PENTAXIM1D "Day of Pentaxim 1 immunization"
 /IM6PENTAXIM1M "Month of Pentaxim 1 immunization"
 /IM6PENTAXIM1Y "Year of Pentaxim 1 immunization"
 /IM6PENTAXIM2D "Day of Pentaxim 2 immunization"
 /IM6PENTAXIM2M "Month of Pentaxim 2 immunization"
 /IM6PENTAXIM2Y "Year of Pentaxim 2 immunization"
 /IM6PENTAXIM3D "Day of Pentaxim 3 immunization"
 /IM6PENTAXIM3M "Month of Pentaxim 3 immunization"
 /IM6PENTAXIM3Y "Year of Pentaxim 3 immunization"
 /IM6HEPB1D "Day of HepB 1 immunization"
 /IM6HEPB1M "Month of HepB 1 immunization"
 /IM6HEPB1Y "Year of HepB 1 immunization"
 /IM6HEPB2D "Day of HepB 2 immunization"
 /IM6HEPB2M "Month of HepB 2 immunization"
 /IM6HEPB2Y "Year of HepB 2 immunization"
 /IM6HEPB3D "Day of HepB 3 immunization"
 /IM6HEPB3M "Month of HepB 3 immunization"
 /IM6HEPB3Y "Year of HepB 3 immunization"
 /IM6RTETRAPENTAD "Day of Rappel Tetraxim ou Pentaxim immunization"
 /IM6RTETRAPENTAM "Month of Rappel Tetraxim ou Pentaxim immunization"
 /IM6RTETRAPENTAY "Year of Rappel Tetraxim ou Pentaxim immunization"
 /IM6PREVSYN1D "Day of Prevanar Synflorix 1 immunization"
 /IM6PREVSYN1M "Month of Prevanar Synflorix 1 immunization"
 /IM6PREVSYN1Y "Year of Prevanar Synflorix 1 immunization"
 /IM6PREVSYN2D "Day of Prevanar Synflorix 2 immunization"
 /IM6PREVSYN2M "Month of Prevanar Synflorix 2 immunization"
 /IM6PREVSYN2Y "Year of Prevanar Synflorix 2 immunization"
 /IM6PREVSYN3D "Day of Prevanar Synflorix 3 immunization"
 /IM6PREVSYN3M "Month of Prevanar Synflorix 3 immunization"
 /IM6PREVSYN3Y "Year of Prevanar Synflorix 3 immunization"
 /IM6PREVSYN4D "Day of Prevanar Synflorix 4 immunization"
 /IM6PREVSYN4M "Month of Prevanar Synflorix 4 immunization"
 /IM6PREVSYN4Y "Year of Prevanar Synflorix 4 immunization"
 /IM6ROTARIX1D "Day of Rotarix 1 immunization"
 /IM6ROTARIX1M "Month of Rotarix 1 immunization"
 /IM6ROTARIX1Y "Year of Rotarix 1 immunization"
 /IM6ROTARIX2D "Day of Rotarix 2 immunization"
 /IM6ROTARIX2M "Month of Rotarix 2 immunization"
 /IM6ROTARIX2Y "Year of Rotarix 2 immunization"
 /IM6ROR1D "Day of Priorix 1 ROR immunization"
 /IM6ROR1M "Month of Priorix 1 ROR immunization"
 /IM6ROR1Y "Year of Priorix 1 ROR immunization"
 /IM6ROR2D "Day of Priorix 2 ROR immunization"
 /IM6ROR2M "Month of Priorix 2 ROR immunization"
 /IM6ROR2Y "Year of Priorix 2 ROR immunization"
 /IM6HAVRIX1D "Day of Havrix 1 immunization"
 /IM6HAVRIX1M "Month of Havrix 1 immunization"
 /IM6HAVRIX1Y "Year of Havrix 1 immunization"
 /IM6HAVRIX2D "Day of Havrix 2 immunization"
 /IM6HAVRIX2M "Month of Havrix 2 immunization"
 /IM6HAVRIX2Y "Year of Havrix 2 immunization"
 /IM9      "Child received any other vaccinations during campaigns, immunization days or child health days"
 /IM11     "Child ever received any vaccinations"
 /IM14     "Child ever given BCG vaccination"
 /IM15     "Hepatitis B vaccination received within 24 hours after birth"
 /IM16     "Child ever given Polio drops"
 /IM18     "Times received Polio drops"
 /IM19     "Child got injection against Polio with last Polio drops"
 /IM19A    "Times received BCG vaccination"
 /IM20     "Child ever given Pentavelent vaccination"
 /IM21     "Times received Pentavelent vaccination"
 /IM26     "Child ever given MMR vaccination"
 /IM26A    "Nombre de prise ROR"
 /IMPP9    "Child received any other vaccinations during campaigns, immunization days or child health days"
 /IMPP11   "Child ever received any vaccinations"
 /IMPP14   "Child ever given BCG vaccination"
 /IMPP15   "Hepatitis B vaccination received within 24 hours after birth"
 /IMPP16   "Child ever given Polio drops"
 /IMPP18   "Times received Polio vaccination"
 /IMPP19   "Child got injection against Polio with last Polio drops"
 /IMPP19A  "Number of injection against Polio "
 /IMPP20A  "Child ever given Pentavelent vaccination"
 /IMPP20C  "Child ever given Pentavelent vaccination"
 /IMPP20B  "Child ever given Pentavelent vaccination"
 /IMPP21A  "Times received Pentavelent vaccination"
 /IMPP21B  "Times received Pentavelent vaccination"
 /IMPP21C  "Times received Pentavelent vaccination"
 /IMPP22   "Child ever given Pneumococcal Conjugate vaccination"
 /IMPP23   "Times received Pneumococcal Conjugate vaccination"
 /IMPP24   "Child ever given Rotavirus vaccination"
 /IMPP25   "Times received Rotavirus vaccination"
 /IMPP26   "Child ever given MMR vaccination"
 /IMPP26A  "Nombre de prise ROR"
 /IMPP29   "Child ever given MMR vaccination"
 /IMPP29A  "Nombre de prise ROR"
 /IMP9     "Child received any other vaccinations during campaigns, immunization days or child health days"
 /IMP11    "Child ever received any vaccinations"
 /IMP14    "Child ever given BCG vaccination"
 /IMP20B   "Child ever given Pentavelent vaccination"
 /IMP21B   "Times received Pentavelent vaccination"
 /IMP20C   "Child ever given Pentavelent vaccination"
 /IMP21C   "Times received Pentavelent vaccination"
 /IMP22    "Child ever given Pneumococcal Conjugate vaccination"
 /IMP23    "Times received Pneumococcal Conjugate vaccination"
 /IMP24    "Child ever given Rotavirus vaccination"
 /IMP25    "Times received Rotavirus vaccination"
 /IMP26    "Child ever given MMR vaccination"
 /IMP26A   "Nombre de prise ROR"
 /IMP29    "Child ever given MMR vaccination"
 /IMP29A   "Nombre de prise ROR"
 /CA1      "Child had diarrhoea in last 2 weeks"
 /CA3      "Child drank less or more during diarrhoea"
 /CA4      "Child ate less or more during diarrhoea"
 /CA5      "Sought advice or treatment for the diarrhoea from any source"
 /CA6A     "Place sought care: (public sector) Government hospital"
 /CA6B     "Place sought care: (public sector) Government health centre"
 /CA6E     "Place sought care: (public sector) Mobile / Outreach clinic"
 /CA6H     "Place sought care: Other public"
 /CA6I     "Place sought care: Private hospital / clinic"
 /CA6J     "Place sought care: Private physician"
 /CA6K     "Place sought care: Private pharmacy"
 /CA6O     "Place sought care: Other private medical"
 /CA6P     "Place sought care: Relative / Friend"
 /CA6Q     "Place sought care: Shop / Market / Street"
 /CA6R     "Place sought care: Traditional practitioner"
 /CA6X     "Place sought care: Other"
 /CA6NR    "Place sought care: Missing"
 /CA7A     "Child given ORS packet solution"
 /CA7B     "Child given ORS fluid"
 /CA7C     "Child given zinc tablets or syrup"
 /CA7D     "Child given homemade solution"
 /CA9A     "Place got ORS: (public sector) Government hospital"
 /CA9B     "Place got ORS: (public sector) Government health centre"
 /CA9E     "Place got ORS: (public sector) Mobile / Outreach clinic"
 /CA9H     "Place got ORS: Other public"
 /CA9I     "Place got ORS: Private hospital / clinic"
 /CA9J     "Place got ORS: Private physician"
 /CA9K     "Place got ORS: Private pharmacy"
 /CA9O     "Place got ORS: Other private medical"
 /CA9P     "Place got ORS: Relative / Friend"
 /CA9Q     "Place got ORS: Shop / Market / Street"
 /CA9R     "Place got ORS: Traditional practitioner"
 /CA9X     "Place got ORS: Other"
 /CA9Z     "Place got ORS: DK /Don't remember"
 /CA9NR    "Place got ORS: Missing"
 /CA11A    "Place got ORS: (public sector) Government hospital"
 /CA11B    "Place got ORS: (public sector) Government health centre"
 /CA11E    "Place got ORS: (public sector) Mobile / Outreach clinic"
 /CA11H    "Place got ORS: Other public"
 /CA11I    "Place got ORS: Private hospital / clinic"
 /CA11J    "Place got ORS: Private physician"
 /CA11K    "Place got ORS: Private pharmacy"
 /CA11O    "Place got ORS: Other private medical"
 /CA11P    "Place got ORS: Relative / Friend"
 /CA11Q    "Place got ORS: Shop / Market / Street"
 /CA11R    "Place got ORS: Traditional practitioner"
 /CA11X    "Place got ORS: Other"
 /CA11Z    "Place got ORS: DK /Don't remember"
 /CA11NR   "Place got ORS: Missing"
 /CA12     "Anything else given to treat the diarrhoea"
 /CA13A    "Other treatment: (Pill or Syrup) Antibiotic"
 /CA13B    "Other treatment (pill or syrup): Antimotility (anti-diarrhoea)"
 /CA13G    "Other treatment (pill or syrup): Other pill or syrup"
 /CA13H    "Other treatment (pill or syrup): Unknown pill or syrup"
 /CA13L    "Other treatment (injection): Antibiotic"
 /CA13M    "Other treatment (injection): Non-antibiotic"
 /CA13N    "Other treatment (injection): Unknown injection"
 /CA13O    "Other treatment: Intravenous (IV)"
 /CA13Q    "Other treatment: Home remedy / Herbal medicine"
 /CA13X    "Other treatment: Other"
 /CA13NR   "Other treatment: Missing"
 /CA14     "Child ill with fever in last 2 weeks"
 /CA16     "Child ill with cough in last 2 weeks"
 /CA17     "Difficulty breathing during illness with cough"
 /CA18     "Symptoms due to problem in chest or blocked nose"
 /CA20     "Sought advice or treatment for illness"
 /CA21A    "Place sought care: (public sector) Government hospital"
 /CA21B    "Place sought care: (public sector) Government health centre"
 /CA21E    "Place sought care: (public sector) Mobile / Outreach clinic"
 /CA21H    "Place sought care: Other public"
 /CA21I    "Place sought care: Private hospital / clinic"
 /CA21J    "Place sought care: Private physician"
 /CA21K    "Place sought care: Private pharmacy"
 /CA21O    "Place sought care: Other private medical"
 /CA21P    "Place sought care: Relative / Friend"
 /CA21Q    "Place sought care: Shop / Market / Street"
 /CA21R    "Place sought care: Traditional practitioner"
 /CA21X    "Place sought care: Other"
 /CA21NR   "Place sought care: Missing"
 /CA22     "Given medicine to treat this illness"
 /CA23L    "Medicine: Antibiotics: Amoxicillin"
 /CA23M    "Medicine: Antibiotics: Cotrimoxazole"
 /CA23N    "Medicine: Antibiotics: Other antibiotic pill / syrup"
 /CA23O    "Medicine: Antibiotics: Other antibiotic injection / IV"
 /CA23R    "Medicine: Paracetamol / Panadol / Acetaminophen"
 /CA23S    "Medicine: Aspirin"
 /CA23T    "Medicine: Ibupropfen"
 /CA23X    "Medicine: Other"
 /CA23Z    "Medicine: DK"
 /CA23NR   "Medicine: Missing"
 /CA25A    "Place got antibiotics:(public sector) Government hospital"
 /CA25B    "Place got antibiotics: (public sector) Government health centre"
 /CA25E    "Place got antibiotics: (public sector) Mobile / Outreach clinic"
 /CA25H    "Place got antibiotics: Other public"
 /CA25I    "Place got antibiotics: Private hospital / clinic"
 /CA25J    "Place got antibiotics: Private physician"
 /CA25K    "Place got antibiotics: Private pharmacy"
 /CA25O    "Place got antibiotics: Other private medical"
 /CA25P    "Place got antibiotics: Relative / Friend"
 /CA25Q    "Place got antibiotics: Shop / Market / Street"
 /CA25R    "Place got antibiotics: Traditional practitioner"
 /CA25X    "Place got antibiotics: Other"
 /CA25Z    "Place got antibiotics: DK / Don't remember"
 /CA25NR   "Place got antibiotics: Missing"
 /CA31     "What was done to dispose of the stools"
 /AN1      "Cluster number"
 /AN2      "Household number"
 /AN3N     "Child's name"
 /AN3      "Child's line number"
 /AN4      "Age of child"
 /AN5N     "Mother's name"
 /AN5      "Mother's line number"
 /AN6      "Interviewer number"
 /AN7N     "Measurer's name"
 /AN7      "Measurer's identification code"
 /AN8      "Child's weight (kilograms)"
 /AN9      "Child undressed to the minimum"
 /AN11     "Child's length or height (centimetres)"
 /AN12     "Child measured lying or standing"
 /AN13D    "Day of measurement"
 /AN13M    "Month of measurement"
 /AN13Y    "Year of measurement"
 /HH4      "Supervisor number"
 /HH6      "Area"
 /HH7      "Region"
 /HL4      "Sex"
 /ED5A     "Highest level of education attended"
 /ED5B     "Highest grade attended at that level"
 /CDOI     "Date of interview child (CMC)"
 /CDOB     "Date of birth of child (CMC)"
 /CAGE     "Age (months)"
 /CAGE_6   "Age"
 /CAGE_11  "Age"
 /CAGED    "Age in days"
 /HAP      "Height for age percentile NCHS"
 /HAZ      "Height for age z-score NCHS"
 /HAM      "Height for age percent of reference median NCHS"
 /WAP      "Weight for age percentile NCHS"
 /WAZ      "Weight for age z-score NCHS"
 /WAM      "Weight for age percent of reference median NCHS"
 /WHP      "Weight for height percentile NCHS"
 /WHZ      "Weight for height z-score NCHS"
 /WHM      "Weight for height percent of reference median NCHS"
 /FLAG     "Flag for anthropometric indicators"
 /BMI      "Body Mass Index WHO"
 /ZBMI     "Body Mass Index z-score WHO"
 /HAZ2     "Height for age z-score WHO"
 /WAZ2     "Weight for age z-score WHO"
 /WHZ2     "Weight for height z-score WHO"
 /HAZFLAG  "Height for age flag WHO"
 /WAZFLAG  "Weight for age flag WHO"
 /WHZFLAG  "Weight for height flag WHO"
 /BMIFLAG  "BMI flag WHO"
 /WHZNOAGE "Weight for height - Age flag WHO"
.
VALUE LABELS
  UF9     
     1 "YES, INTERVIEWED ALREADY"
     2 "NO, FIRST INTERVIEW"
 /UF10    
     1 "YES, PERMISSION IS GIVEN"
     2 "NO, PERMISSION IS NOT GIVEN"
 /UF17    
     1 "COMPLETED"
     2 "NOT AT HOME"
     3 "REFUSED"
     4 "PARTLY COMPLETED"
     5 "INCAPACITATED"
     6 "NO ADULT CONSENT FOR RESPONDENT AGE 15-17"
    96 "OTHER"
 /UF12    
     1 "ARABIC"
     2 "FRENCH"
 /UF13    
     1 "ARABIC"
     2 "FRENCH"
     6 "OTHER"
 /UF14    
     1 "ARABIC"
     2 "FRENCH"
     6 "OTHER"
 /UF15    
     1 "YES, THE ENTIRE QUESTIONNAIRE"
     2 "YES, PARTS OF THE QUESTIONNAIRE"
     3 "NO, NOT USED"
     9 "NO RESPONSE"
 /UB1D    
    98 "DK"
    99 "NO RESPONSE"
 /UB1M    
     1 "JANUARY"
     2 "FEBRUARY"
     3 "MARCH"
     4 "APRIL"
     5 "MAY"
     6 "JUNE"
     7 "JULY"
     8 "AUGUST"
     9 "SEPTEMBER"
    10 "OCTOBER"
    11 "NOVEMBER"
    12 "DECEMBER"
    98 "DK"
    99 "NO RESPONSE"
 /UB1Y    
  9999 "NO RESPONSE"
 /UB6     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UB7     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UB8     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UB9     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UB10A   
  'A' "MUTUAL HEALTH ORGANIZATION / COMMUNITY-BASED HEALTH INSURANCE"
  '?' "NO RESPONSE"
 /UB10D   
  'D' "OTHER PRIVATELY PURCHASED COMMERCIAL HEALTH INSURANCE"
  '?' "NO RESPONSE"
 /UB10E   
  'E' "WHITE CARD"
  '?' "NO RESPONSE"
 /UB10F   
  'F' "YELLOW CARD"
  '?' "NO RESPONSE"
 /UB10X   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /UB10NR  
  '?' "NO RESPONSE"
 /BR1     
     1 "YES, SEEN"
     2 "YES, NOT SEEN"
     3 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BR2     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BR3     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /EC1     
     0 "NONE"
    10 "TEN OR MORE BOOKS"
    99 "NO RESPONSE"
 /EC2A    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /EC2B    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /EC2C    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /EC3A    
     0 "NONE"
     8 "DK"
     9 "NO RESPONSE"
 /EC3B    
     0 "NONE"
     8 "DK"
     9 "NO RESPONSE"
 /EC5AA   
  'A' "MOTHER"
  '?' "NO RESPONSE"
 /EC5AB   
  'B' "FATHER"
  '?' "NO RESPONSE"
 /EC5AX   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /EC5AY   
  'Y' "NO ONE"
  '?' "NO RESPONSE"
 /EC5ANR  
  '?' "NO RESPONSE"
 /EC5BA   
  'A' "MOTHER"
  '?' "NO RESPONSE"
 /EC5BB   
  'B' "FATHER"
  '?' "NO RESPONSE"
 /EC5BX   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /EC5BY   
  'Y' "NO ONE"
  '?' "NO RESPONSE"
 /EC5BNR  
  '?' "NO RESPONSE"
 /EC5CA   
  'A' "MOTHER"
  '?' "NO RESPONSE"
 /EC5CB   
  'B' "FATHER"
  '?' "NO RESPONSE"
 /EC5CX   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /EC5CY   
  'Y' "NO ONE"
  '?' "NO RESPONSE"
 /EC5CNR  
  '?' "NO RESPONSE"
 /EC5DA   
  'A' "MOTHER"
  '?' "NO RESPONSE"
 /EC5DB   
  'B' "FATHER"
  '?' "NO RESPONSE"
 /EC5DX   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /EC5DY   
  'Y' "NO ONE"
  '?' "NO RESPONSE"
 /EC5DNR  
  '?' "NO RESPONSE"
 /EC5EA   
  'A' "MOTHER"
  '?' "NO RESPONSE"
 /EC5EB   
  'B' "FATHER"
  '?' "NO RESPONSE"
 /EC5EX   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /EC5EY   
  'Y' "NO ONE"
  '?' "NO RESPONSE"
 /EC5ENR  
  '?' "NO RESPONSE"
 /EC5FA   
  'A' "MOTHER"
  '?' "NO RESPONSE"
 /EC5FB   
  'B' "FATHER"
  '?' "NO RESPONSE"
 /EC5FX   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /EC5FY   
  'Y' "NO ONE"
  '?' "NO RESPONSE"
 /EC5FNR  
  '?' "NO RESPONSE"
 /EC6     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /EC7     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /EC8     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /EC9     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /EC10    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /EC11    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /EC12    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /EC13    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /EC14    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /EC15    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /UCD2A   
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UCD2B   
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UCD2C   
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UCD2D   
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UCD2E   
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UCD2F   
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UCD2G   
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UCD2H   
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UCD2I   
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UCD2J   
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UCD2K   
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UCD4    
     1 "YES"
     2 "NO"
 /UCD5    
     1 "YES"
     2 "NO"
     8 "DK / NO OPINION"
     9 "NO RESPONSE"
 /UCF2    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UCF3    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UCF4    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UCF7    
     1 "NO DIFFICULTY"
     2 "SOME DIFFICULTY"
     3 "A LOT OF DIFFICULTY"
     4 "CANNOT SEE AT ALL"
     9 "NO RESPONSE"
 /UCF9    
     1 "NO DIFFICULTY"
     2 "SOME DIFFICULTY"
     3 "A LOT OF DIFFICULTY"
     4 "CANNOT SEE AT ALL"
     9 "NO RESPONSE"
 /UCF11   
     2 "SOME DIFFICULTY"
     3 "A LOT OF DIFFICULTY"
     4 "CANNOT WALK AT ALL"
     9 "NO RESPONSE"
 /UCF12   
     1 "NO DIFFICULTY"
     2 "SOME DIFFICULTY"
     3 "A LOT OF DIFFICULTY"
     4 "CANNOT SEE AT ALL"
     9 "NO RESPONSE"
 /UCF13   
     1 "NO DIFFICULTY"
     2 "SOME DIFFICULTY"
     3 "A LOT OF DIFFICULTY"
     4 "CANNOT SEE AT ALL"
     9 "NO RESPONSE"
 /UCF14   
     1 "NO DIFFICULTY"
     2 "SOME DIFFICULTY"
     3 "A LOT OF DIFFICULTY"
     4 "CANNOT SEE AT ALL"
     9 "NO RESPONSE"
 /UCF15   
     1 "NO DIFFICULTY"
     2 "SOME DIFFICULTY"
     3 "A LOT OF DIFFICULTY"
     4 "CANNOT SEE AT ALL"
     9 "NO RESPONSE"
 /UCF16   
     1 "NO DIFFICULTY"
     2 "SOME DIFFICULTY"
     3 "A LOT OF DIFFICULTY"
     4 "CANNOT SEE AT ALL"
     9 "NO RESPONSE"
 /UCF17   
     1 "NO DIFFICULTY"
     2 "SOME DIFFICULTY"
     3 "A LOT OF DIFFICULTY"
     4 "CANNOT SEE AT ALL"
     9 "NO RESPONSE"
 /UCF18   
     1 "NO DIFFICULTY"
     2 "SOME DIFFICULTY"
     3 "A LOT OF DIFFICULTY"
     4 "CANNOT SEE AT ALL"
     9 "NO RESPONSE"
 /UCF19   
     1 "NOT AT ALL"
     2 "LESS"
     3 "THE SAME"
     4 "MORE"
     5 "A LOT MORE"
     9 "NO RESPONSE"
 /BD2     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD3     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD4     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD5     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD6     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD7A    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD7B    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD7C    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD7D    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD7D1   
     7 "7+"
     8 "DK"
     9 "NO RESPONSE"
 /BD7E    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD7E1   
     7 "7+"
     8 "DK"
     9 "NO RESPONSE"
 /BD7X    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD8A    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD8A1   
     7 "7+"
     8 "DK"
     9 "NO RESPONSE"
 /BD8B    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD8C    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD8D    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD8E    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD8F    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD8G    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD8H    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD8I    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD8J    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD8K    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD8L    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD8M    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD8N    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD8X    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /BD9     
     7 "7+"
     8 "DK"
     9 "NO RESPONSE"
 /BD8DUMMY
     1 "Continue"
 /IM2     
     1 "YES, HAVE DOCUMENT"
     4 "NO, DONT HAVE DOCUMENT"
     9 "NO RESPONSE"
 /IM3     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /IM4A    
     1 "PUBLIC"
     2 "PRIVATE"
     3 "BOTH PUBLIC AND PRIVATE"
 /IM4B    
     1 "PUBLIC"
     2 "PRIVATE"
     3 "BOTH PUBLIC AND PRIVATE"
 /IM5     
     1 "YES, ONLY PUBLIC CARD(S) SEEN"
     2 "YES, PRIVATE CARDS SEEN"
     3 "YES, BOTH PUBLIC AND PRIVATE CARDS SEEN"
     4 "NO PUBLIC CARDS  SEEN"
     5 "NO PRIVATE CARDS SEEN"
     6 "NIGTHER PUBLIC NOR PRIVATE CARDS SEEN"
     9 "NO RESPONSE"
 /IM6BD   
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6BM   
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6BY   
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6H0D  
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6H0M  
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6H0Y  
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6VPO1D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6VPO1M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6VPO1Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6VPO2D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6VPO2M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6VPO2Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6VPO3D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6VPO3M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6VPO3Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6VPI1D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6VPI1M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6VPI1Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6VPI2D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6VPI2M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6VPI2Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6PENTA1D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PENTA1M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PENTA1Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6PENTA2D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PENTA2M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PENTA2Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6PENTA3D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PENTA3M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PENTA3Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6RR1D 
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6RR1M 
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6RR1Y 
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6RR2D 
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6RR2M 
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6RR2Y 
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6DTCPRD
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6DTCPRM
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6DTCPRY
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6INFHEXA1D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6INFHEXA1M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6INFHEXA1Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6INFHEXA2D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6INFHEXA2M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6INFHEXA2Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6INFHEXA3D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6INFHEXA3M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6INFHEXA3Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6PENTAXIM1D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PENTAXIM1M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PENTAXIM1Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6PENTAXIM2D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PENTAXIM2M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PENTAXIM2Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6PENTAXIM3D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PENTAXIM3M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PENTAXIM3Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6HEPB1D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6HEPB1M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6HEPB1Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6HEPB2D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6HEPB2M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6HEPB2Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6HEPB3D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6HEPB3M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6HEPB3Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6RTETRAPENTAD
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6RTETRAPENTAM
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6RTETRAPENTAY
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6PREVSYN1D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PREVSYN1M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PREVSYN1Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6PREVSYN2D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PREVSYN2M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PREVSYN2Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6PREVSYN3D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PREVSYN3M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PREVSYN3Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6PREVSYN4D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PREVSYN4M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6PREVSYN4Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6ROTARIX1D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6ROTARIX1M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6ROTARIX1Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6ROTARIX2D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6ROTARIX2M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6ROTARIX2Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6ROR1D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6ROR1M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6ROR1Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6ROR2D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6ROR2M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6ROR2Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6HAVRIX1D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6HAVRIX1M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6HAVRIX1Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM6HAVRIX2D
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6HAVRIX2M
     0 "NOT GIVEN"
    44 "MARKED ON CARD"
    66 "MOTHER REPORTED"
    99 "NO RESPONSE"
 /IM6HAVRIX2Y
     0 "NOT GIVEN"
  4444 "MARKED ON CARD"
  6666 "MOTHER REPORTED"
  9999 "NO RESPONSE"
 /IM9     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IM11    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IM14    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IM15    
     1 "YES, WITHIN 24 HOURS"
     2 "YES, BUT NOT WITHIN 24 HOURS"
     3 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IM16    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IM18    
     8 "DK"
     9 "NO RESPONSE"
 /IM19    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IM19A   
     8 "DK"
     9 "NO RESPONSE"
 /IM20    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IM21    
     8 "DK"
     9 "NO RESPONSE"
 /IM26    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IM26A   
     8 "DK"
     9 "NO RESPONSE"
 /IMPP9   
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMPP11  
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMPP14  
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMPP15  
     1 "YES, WITHIN 24 HOURS"
     2 "YES, BUT NOT WITHIN 24 HOURS"
     3 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMPP16  
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMPP18  
     8 "DK"
     9 "NO RESPONSE"
 /IMPP19  
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMPP19A 
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMPP20A 
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMPP20C 
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMPP20B 
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMPP21A 
     8 "DK"
     9 "NO RESPONSE"
 /IMPP21B 
     8 "DK"
     9 "NO RESPONSE"
 /IMPP21C 
     8 "DK"
     9 "NO RESPONSE"
 /IMPP22  
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMPP23  
     8 "DK"
     9 "NO RESPONSE"
 /IMPP24  
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMPP25  
     8 "DK"
     9 "NO RESPONSE"
 /IMPP26  
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMPP26A 
     8 "DK"
     9 "NO RESPONSE"
 /IMPP29  
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMPP29A 
     8 "DK"
     9 "NO RESPONSE"
 /IMP9    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMP11   
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMP14   
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMP20B  
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMP21B  
     8 "DK"
     9 "NO RESPONSE"
 /IMP20C  
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMP21C  
     8 "DK"
     9 "NO RESPONSE"
 /IMP22   
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMP23   
     8 "DK"
     9 "NO RESPONSE"
 /IMP24   
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMP25   
     8 "DK"
     9 "NO RESPONSE"
 /IMP26   
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMP26A  
     8 "DK"
     9 "NO RESPONSE"
 /IMP29   
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /IMP29A  
     8 "DK"
     9 "NO RESPONSE"
 /CA1     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /CA3     
     1 "MUCH LESS"
     2 "SOMEWHAT LESS"
     3 "ABOUT THE SAME"
     4 "MORE"
     5 "NOTHING TO DRINK"
     8 "DK"
     9 "NO RESPONSE"
 /CA4     
     1 "MUCH LESS"
     2 "SOMEWHAT LESS"
     3 "ABOUT THE SAME"
     4 "MORE"
     5 "STOPPED FOOD"
     7 "NEVER GAVE FOOD"
     8 "DK"
     9 "NO RESPONSE"
 /CA5     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /CA6A    
  'A' "GOVERNMENT HOSPITAL"
  '?' "NO RESPONSE"
 /CA6B    
  'B' "GOVERNMENT HEALTH CENTRE"
  '?' "NO RESPONSE"
 /CA6E    
  'E' "MOBILE / OUTREACH CLINIC"
  '?' "NO RESPONSE"
 /CA6H    
  'H' "OTHER PUBLIC MEDICAL"
  '?' "NO RESPONSE"
 /CA6I    
  'I' "PRIVATE HOSPITAL / CLINIC"
  '?' "NO RESPONSE"
 /CA6J    
  'J' "PRIVATE PHYSICIAN"
  '?' "NO RESPONSE"
 /CA6K    
  'K' "PRIVATE PHARMACY"
  '?' "NO RESPONSE"
 /CA6O    
  'O' "OTHER PRIVATE MEDICAL"
  '?' "NO RESPONSE"
 /CA6P    
  'P' "RELATIVE / FRIEND"
  '?' "NO RESPONSE"
 /CA6Q    
  'Q' "SHOP / MARKET / STREET"
  '?' "NO RESPONSE"
 /CA6R    
  'R' "TRADITIONAL PRACTITIONER"
  '?' "NO RESPONSE"
 /CA6X    
  'X' "OTHER"
  '?' "NO RESPONSE"
 /CA7A    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /CA7B    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /CA7C    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /CA7D    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /CA9A    
  'A' "GOVERNMENT HOSPITAL"
  '?' "NO RESPONSE"
 /CA9B    
  'B' "GOVERNMENT HEALTH CENTRE"
  '?' "NO RESPONSE"
 /CA9E    
  'E' "MOBILE / OUTREACH CLINIC"
  '?' "NO RESPONSE"
 /CA9H    
  'H' "OTHER PUBLIC MEDICAL"
  '?' "NO RESPONSE"
 /CA9I    
  'I' "PRIVATE HOSPITAL / CLINIC"
  '?' "NO RESPONSE"
 /CA9J    
  'J' "PRIVATE PHYSICIAN"
  '?' "NO RESPONSE"
 /CA9K    
  'K' "PRIVATE PHARMACY"
  '?' "NO RESPONSE"
 /CA9O    
  'O' "OTHER PRIVATE MEDICAL"
  '?' "NO RESPONSE"
 /CA9P    
  'P' "RELATIVE / FRIEND"
  '?' "NO RESPONSE"
 /CA9Q    
  'Q' "SHOP / MARKET / STREET"
  '?' "NO RESPONSE"
 /CA9R    
  'R' "TRADITIONAL PRACTITIONER"
  '?' "NO RESPONSE"
 /CA9X    
  'X' "OTHER"
  '?' "NO RESPONSE"
 /CA9Z    
  'Z' "DK/DON’T REMEMBER"
  '?' "NO RESPONSE"
 /CA11A   
  'A' "GOVERNMENT HOSPITAL"
  '?' "NO RESPONSE"
 /CA11B   
  'B' "GOVERNMENT HEALTH CENTRE"
  '?' "NO RESPONSE"
 /CA11E   
  'E' "MOBILE / OUTREACH CLINIC"
  '?' "NO RESPONSE"
 /CA11H   
  'H' "OTHER PUBLIC MEDICAL"
  '?' "NO RESPONSE"
 /CA11I   
  'I' "PRIVATE HOSPITAL / CLINIC"
  '?' "NO RESPONSE"
 /CA11J   
  'J' "PRIVATE PHYSICIAN"
  '?' "NO RESPONSE"
 /CA11K   
  'K' "PRIVATE PHARMACY"
  '?' "NO RESPONSE"
 /CA11O   
  'O' "OTHER PRIVATE MEDICAL"
  '?' "NO RESPONSE"
 /CA11P   
  'P' "RELATIVE / FRIEND"
  '?' "NO RESPONSE"
 /CA11Q   
  'Q' "SHOP / MARKET / STREET"
  '?' "NO RESPONSE"
 /CA11R   
  'R' "TRADITIONAL PRACTITIONER"
  '?' "NO RESPONSE"
 /CA11X   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /CA11Z   
  'Z' "DK/DON’T REMEMBER"
  '?' "NO RESPONSE"
 /CA12    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /CA13A   
  'A' "PILL OR SYRUP: ANTIBIOTIC"
  '?' "NO RESPONSE"
 /CA13B   
  'B' "PILL OR SYRUP: ANTIMOTILITY (ANTI-DIARRHOEA)"
  '?' "NO RESPONSE"
 /CA13G   
  'G' "PILL OR SYRUP: OTHER PILL OR SYRUP"
  '?' "NO RESPONSE"
 /CA13H   
  'H' "PILL OR SYRUP: UNKNOWN PILL OR SYRUP"
  '?' "NO RESPONSE"
 /CA13L   
  'L' "INJECTION: ANTIBIOTIC"
  '?' "NO RESPONSE"
 /CA13M   
  'M' "INJECTION: NON-ANTIBIOTIC"
  '?' "NO RESPONSE"
 /CA13N   
  'N' "INJECTION: UNKNOWN INJECTION"
  '?' "NO RESPONSE"
 /CA13O   
  'O' "INTRAVENOUS (IV)"
  '?' "NO RESPONSE"
 /CA13Q   
  'Q' "HOME REMEDY / HERBAL MEDICINE"
  '?' "NO RESPONSE"
 /CA13X   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /CA14    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /CA16    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /CA17    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /CA18    
     1 "PROBLEM IN CHEST ONLY"
     2 "BLOCKED OR RUNNY NOSE ONLY"
     3 "BOTH"
     6 "OTHER"
     8 "NO RESPONSE"
 /CA20    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /CA21A   
  'A' "GOVERNMENT HOSPITAL"
  '?' "NO RESPONSE"
 /CA21B   
  'B' "GOVERNMENT HEALTH CENTRE"
  '?' "NO RESPONSE"
 /CA21E   
  'E' "MOBILE / OUTREACH CLINIC"
  '?' "NO RESPONSE"
 /CA21H   
  'H' "OTHER PUBLIC MEDICAL"
  '?' "NO RESPONSE"
 /CA21I   
  'I' "PRIVATE HOSPITAL / CLINIC"
  '?' "NO RESPONSE"
 /CA21J   
  'J' "PRIVATE PHYSICIAN"
  '?' "NO RESPONSE"
 /CA21K   
  'K' "PRIVATE PHARMACY"
  '?' "NO RESPONSE"
 /CA21O   
  'O' "OTHER PRIVATE MEDICAL"
  '?' "NO RESPONSE"
 /CA21P   
  'P' "RELATIVE / FRIEND"
  '?' "NO RESPONSE"
 /CA21Q   
  'Q' "SHOP / MARKET / STREET"
  '?' "NO RESPONSE"
 /CA21R   
  'R' "TRADITIONAL PRACTITIONER"
  '?' "NO RESPONSE"
 /CA21X   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /CA22    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /CA23L   
  'L' "ANTIBIOTICS: AMOXICILLIN"
  '?' "NO RESPONSE"
 /CA23M   
  'M' "ANTIBIOTICS: COTRIMOXAZOLE"
  '?' "NO RESPONSE"
 /CA23N   
  'N' "ANTIBIOTICS: OTHER ANTIBIOTIC PILL/SYRUP"
  '?' "NO RESPONSE"
 /CA23O   
  'O' "ANTIBIOTICS: OTHER ANTIBIOTIC INJECTION/IV"
  '?' "NO RESPONSE"
 /CA23R   
  'R' "PARACETAMOL/PANADOL/ACETAMINOPHEN"
  '?' "NO RESPONSE"
 /CA23S   
  'S' "ASPIRIN"
  '?' "NO RESPONSE"
 /CA23T   
  'T' "IBUPROFEN"
  '?' "NO RESPONSE"
 /CA23X   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /CA23Z   
  'Z' "DK"
  '?' "NO RESPONSE"
 /CA25A   
  'A' "GOVERNMENT HOSPITAL"
  '?' "NO RESPONSE"
 /CA25B   
  'B' "GOVERNMENT HEALTH CENTRE"
  '?' "NO RESPONSE"
 /CA25E   
  'E' "MOBILE / OUTREACH CLINIC"
  '?' "NO RESPONSE"
 /CA25H   
  'H' "OTHER PUBLIC MEDICAL"
  '?' "NO RESPONSE"
 /CA25I   
  'I' "PRIVATE HOSPITAL / CLINIC"
  '?' "NO RESPONSE"
 /CA25J   
  'J' "PRIVATE PHYSICIAN"
  '?' "NO RESPONSE"
 /CA25K   
  'K' "PRIVATE PHARMACY"
  '?' "NO RESPONSE"
 /CA25O   
  'O' "OTHER PRIVATE MEDICAL"
  '?' "NO RESPONSE"
 /CA25P   
  'P' "RELATIVE / FRIEND"
  '?' "NO RESPONSE"
 /CA25Q   
  'Q' "SHOP / MARKET / STREET"
  '?' "NO RESPONSE"
 /CA25R   
  'R' "TRADITIONAL PRACTITIONER"
  '?' "NO RESPONSE"
 /CA25X   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /CA25Z   
  'Z' "DK/DON’T REMEMBER"
  '?' "NO RESPONSE"
 /CA31    
     1 "CHILD USED TOILET / LATRINE"
     2 "PUT / RINSED INTO: TOILET OR LATRINE"
     3 "PUT / RINSED INTO: DRAIN OR DITCH"
     4 "THROWN INTO GARBAGE (SOLID WASTE)"
     5 "BURIED"
     6 "LEFT IN THE OPEN"
    96 "OTHER"
    98 "DK"
    99 "NO RESPONSE"
 /AN8     
  99,3 "CHILD NOT PRESENT"
  99,4 "CHILD REFUSED"
  99,5 "RESPONDENT REFUSED"
  99,6 "OTHER"
  99,9 "NO RESPONSE"
 /AN9     
     1 "YES"
     2 "NO, THE CHILD COULD NOT BE UNDRESSED TO THE MINIMUM"
     9 "NO RESPONSE"
 /AN11    
  999,4 "CHILD REFUSED"
  999,5 "RESPONDENT REFUSED"
  999,6 "OTHER"
  999,9 "NO RESPONSE"
 /AN12    
     1 "LYING DOWN"
     2 "STANDING UP"
     9 "NO RESPONSE"
 /HH6     
     1 "URBAIN"
     2 "RURAL"
 /HH7     
     1 "DISTRICT TUNIS"
     2 "NORD EST"
     3 "NORD OUEST"
     4 "CENTRE EST"
     5 "CENTRE OUEST"
     6 "SUD EST"
     7 "SUD OUEST"
 /HL4     
     1 "MALE"
     2 "FEMALE"
 /ED5A    
     0 "ECE"
     1 "PRIMARY"
     2 "LOWER SECONDARY"
     3 "UPPER SECONDARY"
     4 "HIGHER"
     5 "ADULT EDUCATION"
     8 "DK"
     9 "NO RESPONSE"
 /ED5B    
    97 "INCONSISTENT"
    98 "DK"
    99 "NO RESPONSE"
 /CAGE_6  
     1 "0-5"
     2 "6-11"
     3 "12-23"
     4 "24-35"
     5 "36-47"
     6 "48-59"
 /CAGE_11 
     1 "0-11"
     2 "12-23"
     3 "24-35"
     4 "36-47"
     5 "48-59"
 /FLAG    
     0 "No flag"
     1 "Height for age"
     2 "Weight for height"
     3 "Weight for height, Height for age"
     4 "Weight for age"
     5 "Weight for age, Height for age"
     6 "Weight for age, Weight for height"
     7 "Weight for age, Weight for height, Height for age"
 /BMI     
  99,97 "Measurement out of range"
  99,99 "Not measured"
 /ZBMI    
  99,97 "Measurement out of range"
  99,98 "Z-score out of range"
  99,99 "Not measured"
 /HAZ2    
  99,97 "Measurement out of range"
  99,98 "Z-score out of range"
  99,99 "Not measured"
 /WAZ2    
  99,97 "Measurement out of range"
  99,98 "Z-score out of range"
  99,99 "Not measured"
 /WHZ2    
  99,97 "Measurement out of range"
  99,98 "Z-score out of range"
  99,99 "Not measured"
 /HAZFLAG 
     0 "No error"
     1 "Error flag"
 /WAZFLAG 
     0 "No error"
     1 "Error flag"
 /WHZFLAG 
     0 "No error"
     1 "Error flag"
 /BMIFLAG 
     0 "No error"
     1 "Error flag"
 /WHZNOAGE
     0 "Age given - all measurements calculated"
     1 "No age - only weight for height calculated"
.
EXECUTE.
