DATA LIST FILE='C:\MICS6TUN\SPSS\MYWM.DAT' RECORDS=1
 /
 HH1         1-3   
 HH2         4-5   
 WM1         6-8   
 WM2         9-10  
 WMINT      11-13  
 WM3        14-15  
 LN         16-17  
 WM3A       18-97   (A)
 WM4        98-100 
 WM5       101-103 
 WM6D      104-105 
 WM6M      106-107 
 WM6Y      108-111 
 WM8       112-112 
 WM9       113-113 
 WM17      114-115 
 WM7H      116-117 
 WM7M      118-119 
 WM10H     120-121 
 WM10M     122-123 
 WM11      124-124 
 WM12      125-125 
 WM13      126-126 
 WM14      127-127 
 WM15      128-128 
 WMHINT    129-131 
 WB3M      132-133 
 WB3Y      134-137 
 WB4       138-139 
 WB5       140-140 
 WB6A      141-141 
 WB6B      142-143 
 WB7       144-144 
 WB9       145-145 
 WB10A     146-147 
 WB10B     148-149 
 WB11      150-150 
 WB12A     151-152 
 WB12B     153-154 
 WB14      155-155 
 WB15      156-157 
 WB16      158-158 
 WB17      159-160 
 WB18      161-161 
 WB19A     162-165  (A)
 WB19D     166-169  (A)
 WB19E     170-173  (A)
 WB19F     174-177  (A)
 WB19X     178-181  (A)
 WB19NR    182-185  (A)
 WDOI      186-189 
 WB3C      190-193 
 WB3F      194-194 
 WB4C      195-196 
 WAGE      197-197 
 MT1       198-198 
 MT2       199-199 
 MT3       200-200 
 MT4       201-201 
 MT5       202-202 
 MT6A      203-203 
 MT6B      204-204 
 MT6C      205-205 
 MT6D      206-206 
 MT6E      207-207 
 MT6F      208-208 
 MT6G      209-209 
 MT6H      210-210 
 MT6I      211-211 
 MT9       212-212 
 MT10      213-213 
 MT11      214-214 
 MT12      215-215 
 CM1       216-216 
 CM2       217-217 
 CM3       218-219 
 CM4       220-221 
 CM5       222-222 
 CM6       223-224 
 CM7       225-226 
 CM8       227-227 
 CM9       228-229 
 CM10      230-231 
 CM11      232-233 
 CM12      234-234 
 CM15      235-235 
 CM17      236-236 
 CM18      237-316  (A)
 BH11      317-317 
 DB2       318-318 
 DB4       319-319 
 MN2       320-320 
 MN3A      321-324  (A)
 MN3B      325-328  (A)
 MN3F      329-332  (A)
 MN3X      333-336  (A)
 MN3NR     337-340  (A)
 MN4AU     341-341 
 MN4AN     342-343 
 MN5       344-345 
 MN6A      346-346 
 MN6B      347-347 
 MN6C      348-348 
 MN8       349-349 
 MN9       350-350 
 MN11      351-351 
 MN12      352-352 
 MN14      353-354 
 MN19A     355-358  (A)
 MN19B     359-362  (A)
 MN19F     363-366  (A)
 MN19H     367-370  (A)
 MN19X     371-374  (A)
 MN19Y     375-378  (A)
 MN19NR    379-382  (A)
 MN20      383-384 
 MN21      385-385 
 MN22      386-386 
 MN23      387-387 
 MN24      388-388 
 MN25      389-389 
 MN26U     390-390 
 MN26N     391-392 
 MN28      393-393 
 MN29      394-394 
 MN30      395-395 
 MN31A     396-399  (A)
 MN31B     400-403  (A)
 MN31X     404-407  (A)
 MN31Z     408-411  (A)
 MN31NR    412-415  (A)
 MN32      416-416 
 MN33      417-417 
 MN34A     418-418 
 MN34      419-423  (3)
 MN35      424-424 
 MN36      425-425 
 MN37U     426-426 
 MN37N     427-428 
 MN38      429-429 
 MN39A     430-433  (A)
 MN39B     434-437  (A)
 MN39C     438-441  (A)
 MN39D     442-445  (A)
 MN39E     446-449  (A)
 MN39F     450-453  (A)
 MN39G     454-457  (A)
 MN39H     458-461  (A)
 MN39I     462-465  (A)
 MN39J     466-469  (A)
 MN39X     470-473  (A)
 MN39Y     474-477  (A)
 MN39NR    478-481  (A)
 PN3U      482-482 
 PN3N      483-484 
 PN4       485-485 
 PN5       486-486 
 PN6       487-487 
 PN8       488-488 
 PN9       489-489 
 PN10      490-490 
 PN11      491-491 
 PN12      492-492 
 PN13U     493-493 
 PN13N     494-495 
 PN14A     496-499  (A)
 PN14B     500-503  (A)
 PN14F     504-507  (A)
 PN14H     508-511  (A)
 PN14X     512-515  (A)
 PN14NR    516-519  (A)
 PN15      520-521 
 PN17      522-522 
 PN19      523-523 
 PN20      524-524 
 PN21      525-525 
 PN22U     526-526 
 PN22N     527-528 
 PN23A     529-532  (A)
 PN23B     533-536  (A)
 PN23F     537-540  (A)
 PN23H     541-544  (A)
 PN23X     545-548  (A)
 PN23NR    549-552  (A)
 PN24      553-554 
 PN25A     555-555 
 PN25B     556-556 
 PN25C     557-557 
 PN27      558-558 
 PN29      559-559 
 PN30      560-560 
 CP1       561-561 
 CP2       562-562 
 CP3       563-563 
 CP4A      564-567  (A)
 CP4B      568-571  (A)
 CP4C      572-575  (A)
 CP4D      576-579  (A)
 CP4E      580-583  (A)
 CP4F      584-587  (A)
 CP4G      588-591  (A)
 CP4H      592-595  (A)
 CP4I      596-599  (A)
 CP4J      600-603  (A)
 CP4K      604-607  (A)
 CP4L      608-611  (A)
 CP4M      612-615  (A)
 CP4X      616-619  (A)
 CP4NR     620-623  (A)
 UN2       624-624 
 UN4       625-625 
 UN5       626-626 
 UN7       627-627 
 UN8U      628-628 
 UN8N      629-630 
 UN11      631-631 
 UN12A     632-635  (A)
 UN12B     636-639  (A)
 UN12C     640-643  (A)
 UN12D     644-647  (A)
 UN12E     648-651  (A)
 UN12F     652-655  (A)
 UN12G     656-659  (A)
 UN12H     660-663  (A)
 UN12I     664-667  (A)
 UN12X     668-671  (A)
 UN12Z     672-675  (A)
 UN12NR    676-679  (A)
 UN14U     680-680 
 UN14N     681-682 
 UN16      683-683 
 UN17      684-684 
 UN18      685-685 
 UN19      686-686 
 DV1A      687-687 
 DV1B      688-688 
 DV1C      689-689 
 DV1D      690-690 
 DV1E      691-691 
 VT1       692-692 
 VT2       693-693 
 VT3       694-694 
 VT5       695-695 
 VT6       696-696 
 VT7A      697-700  (A)
 VT7B      701-704  (A)
 VT7X      705-708  (A)
 VT7NR     709-712  (A)
 VT8       713-713 
 VT9       714-714 
 VT10      715-715 
 VT11      716-716 
 VT12      717-718 
 VT13      719-719 
 VT14      720-720 
 VT17      721-721 
 VT18A     722-725  (A)
 VT18B     726-729  (A)
 VT18X     730-733  (A)
 VT18NR    734-737  (A)
 VT19      738-738 
 VT20      739-739 
 VT21      740-740 
 VT22A     741-741 
 VT22B     742-742 
 VT22C     743-743 
 VT22D     744-744 
 VT22F     745-745 
 VT22X     746-746 
 MA1       747-747 
 MA2       748-749 
 MA5       750-750 
 MA6       751-751 
 MA7       752-752 
 MA8M      753-754 
 MA8Y      755-758 
 MA11      759-760 
 MA8C      761-764 
 MA8F      765-765 
 MA11C     766-767 
 AF2       768-768 
 AF3       769-769 
 AF6       770-770 
 AF8       771-771 
 AF9       772-772 
 AF10      773-773 
 AF11      774-774 
 AF12      775-775 
 HA1       776-776 
 HA2       777-777 
 HA3       778-778 
 HA4       779-779 
 HA5       780-780 
 HA6       781-781 
 HA7       782-782 
 HA8A      783-783 
 HA8B      784-784 
 HA8C      785-785 
 HA10      786-786 
 HA13A     787-787 
 HA13B     788-788 
 HA13C     789-789 
 HA13D     790-790 
 HA14      791-791 
 HA15      792-792 
 HA16      793-793 
 HA18      794-794 
 HA19      795-795 
 HA20      796-796 
 HA22      797-797 
 HA23      798-798 
 HA24      799-799 
 HA25      800-800 
 HA26      801-801 
 HA27      802-802 
 HA28      803-803 
 HA29      804-804 
 HA30      805-805 
 HA31      806-806 
 HA32      807-807 
 HA33      808-808 
 HA34      809-809 
 HA35      810-810 
 HA36      811-811 
 TA1       812-812 
 TA2       813-814 
 TA3       815-815 
 TA4       816-817 
 TA5       818-819 
 TA6       820-820 
 TA7       821-821 
 TA8A      822-825  (A)
 TA8B      826-829  (A)
 TA8C      830-833  (A)
 TA8D      834-837  (A)
 TA8X      838-841  (A)
 TA8NR     842-845  (A)
 TA9       846-847 
 TA10      848-848 
 TA11      849-849 
 TA12B     850-853  (A)
 TA12X     854-857  (A)
 TA12NR    858-861  (A)
 TA13      862-863 
 TA14      864-864 
 TA15      865-866 
 TA16      867-868 
 TA17      869-870 
 HH4       871-873 
 HH6       874-874 
 HH7       875-875 
 WDOB      876-879 
 WDOM      880-883 
 WAGEM     884-885 
 WDOBFC    886-889 
 WDOBLC    890-893 
 SEXLASTC  894-894 
 MSTATUS   895-895 
 CEB       896-897 
 CSURV     898-899 
 CDEAD     900-901 
.
VARIABLE LABELS
  HH1      "Cluster number"
 /HH2      "Household number"
 /WM1      "Cluster number"
 /WM2      "Household number"
 /WMINT    "Interviewer number"
 /WM3      "Woman's line number"
 /LN       "Line number"
 /WM3A     "Woman's name"
 /WM4      "Supervisor’s number"
 /WM5      "Interviewer’s number"
 /WM6D     "Day of interview"
 /WM6M     "Month of interview"
 /WM6Y     "Year of interview"
 /WM8      "Household interviewer"
 /WM9      "Consent"
 /WM17     "Result of woman's interview"
 /WM7H     "Start of interview - Hour"
 /WM7M     "Start of interview - Minutes"
 /WM10H    "End of interview - Hour"
 /WM10M    "End of interview - Minutes"
 /WM11     "Interview completed in private"
 /WM12     "Language of the Questionnaire"
 /WM13     "Language of the Interview"
 /WM14     "Native language of the Respondent"
 /WM15     "Translator used"
 /WMHINT   "Household interviewer"
 /WB3M     "Month of birth of woman"
 /WB3Y     "Year of birth of woman"
 /WB4      "Age of woman"
 /WB5      "Ever attended school"
 /WB6A     "Highest level of school attended"
 /WB6B     "Highest grade attended at that level"
 /WB7      "Grade completion"
 /WB9      "Attended school during current school year"
 /WB10A    "Level of education attended current school year"
 /WB10B    "Grade of education attended current school year"
 /WB11     "Attended school previous school year"
 /WB12A    "Level of education attended previous school year"
 /WB12B    "Grade of education attended previous school year"
 /WB14     "Can read part of the sentence"
 /WB15     "Duration of living in current place"
 /WB16     "Place of living prior to moving to current place"
 /WB17     "Region prior to moving to current place"
 /WB18     "Covered by health insurance"
 /WB19A    "Type of health insurance: Mutual health organization"
 /WB19D    "Type of health insurance: Other privately purchased commercial health insurance"
 /WB19E    "Type of health insurance: Health insurance through employer"
 /WB19F    "Type of health insurance: Social security"
 /WB19X    "Type of health insurance: Other"
 /WB19NR   "Type of health insurance: No response"
 /WDOI     "Date of interview women (CMC)"
 /WB3C     "Date of birth of woman (CMC)"
 /WB3F     "Date flag for WB1"
 /WB4C     "Age of respondent (calculated)"
 /WAGE     "Age"
 /MT1      "Frequency of reading newspaper or magazine"
 /MT2      "Frequency of listening to the radio"
 /MT3      "Frequency of watching TV"
 /MT4      "Ever used a computer or a tablet"
 /MT5      "Computer / tablet usage in the last 3 months"
 /MT6A     "During the last 3 months: Copy or move a file or folder"
 /MT6B     "During the last 3 months: Use a copy / paste in document"
 /MT6C     "During the last 3 months: Send e-mail with attached file"
 /MT6D     "During the last 3 months: Use a basic arithmetic formula in a 	spreadsheet"
 /MT6E     "During the last 3 months: Connect and install a new device"
 /MT6F     "During the last 3 months: Install and configure software"
 /MT6G     "During the last 3 months: Create an electronic presentation"
 /MT6H     "During the last 3 months: Transfer a file"
 /MT6I     "During the last 3 months: Write a computer program"
 /MT9      "Ever used internet"
 /MT10     "Internet usage in the last 3 months"
 /MT11     "Own a mobile phone"
 /MT12     "Mobile phone usage in the last 3 months"
 /CM1      "Ever given birth"
 /CM2      "Any sons or daughters living with you"
 /CM3      "Sons living with you"
 /CM4      "Daughters living with you"
 /CM5      "Any sons or daughters not living with you"
 /CM6      "Sons living elsewhere"
 /CM7      "Daughters living elsewhere"
 /CM8      "Ever had child who later died"
 /CM9      "Boys dead"
 /CM10     "Girls dead"
 /CM11     "Children ever born"
 /CM12     "Confirm total number of ever born"
 /CM15     "Check total number of children ever born"
 /CM17     "Live births in last two years"
 /CM18     "Name of the last born child"
 /BH11     "Any other live births"
 /DB2      "Wanted last child then"
 /DB4      "Wanted child later or did not want more children"
 /MN2      "Received prenatal care"
 /MN3A     "Prenatal care provider: Doctor"
 /MN3B     "Prenatal care provider: Nurse/Midwife"
 /MN3F     "Prenatal care provider: Traditional birth attendant"
 /MN3X     "Prenatal care provider: Other"
 /MN3NR    "Prenatal care provider: No Response"
 /MN4AU    "Weeks or months pregnent at first prenatal care - unit"
 /MN4AN    "Weeks or months pregnant at first prenatal care - number"
 /MN5      "Times received prenatal care"
 /MN6A     "Blood pressure"
 /MN6B     "Urine sample"
 /MN6C     "Blood sample"
 /MN8      "Any tetanus toxoid injection during last pregnancy"
 /MN9      "Doses of tetanus toxoid during last pregnancy"
 /MN11     "Any tetanus toxoid injection before last pregnancy"
 /MN12     "Doses of tetanus toxoid before last pregnancy"
 /MN14     "Years ago last tetanus toxoid received before last pregnancy"
 /MN19A    "Assistance at delivery: Doctor"
 /MN19B    "Assistance at delivery: Nurse / Midwife"
 /MN19F    "Assistance at delivery: Traditional birth attendant"
 /MN19H    "Assistance at delivery: Relative / Friend"
 /MN19X    "Assistance at delivery: Other"
 /MN19Y    "Assistance at delivery: No one"
 /MN19NR   "Assistance at delivery: No response"
 /MN20     "Place of delivery"
 /MN21     "Delivery by caesarean section"
 /MN22     "Decision made to have caesarean section"
 /MN23     "After the birth, baby was put directly on the bare skin of mothers chest"
 /MN24     "Baby was wrapped up before being placed on mothers chest"
 /MN25     "Baby was dried or wiped soon after birth"
 /MN26U    "Time baby was bathed - unit"
 /MN26N    "Time baby was bathed - number"
 /MN28     "What was used to cut the cord"
 /MN29     "Instrument used to cut the cord boiled prior to use"
 /MN30     "Something applied to the cord after it was cut"
 /MN31A    "What was applied to the cord: Chlorhexidine"
 /MN31B    "What was applied to the cord: Other antiseptic"
 /MN31X    "What was applied to the cord: Other"
 /MN31Z    "What was applied to the cord: DK / Don't remember"
 /MN31NR   "What was applied to the cord: No Response"
 /MN32     "Size of child at birth"
 /MN33     "Weighted at birth"
 /MN34A    "Weight from card or recall"
 /MN34     "Weight at birth (Kilograms)"
 /MN35     "Menstrual period returned since the birth of child"
 /MN36     "Ever breastfeed"
 /MN37U    "Time baby put to breast - unit"
 /MN37N    "Time baby put to breast - number"
 /MN38     "Within first 3 days after delivery, child given anything to drink other than breast milk"
 /MN39A    "Child given to drink: Milk (other than breast milk)"
 /MN39B    "Child given to drink: Plain water"
 /MN39C    "Child given to drink: Sugar or glucose water"
 /MN39D    "Child given to drink: Gripe water"
 /MN39E    "Child given to drink: Sugar - salt - water solution"
 /MN39F    "Child given to drink: Fruit juice"
 /MN39G    "Child given to drink: Infant formula"
 /MN39H    "Child given to drink: Tea / Infusions"
 /MN39I    "Child given to drink: Honey"
 /MN39J    "Child given to drink: Prescribed medicine"
 /MN39X    "Child given to drink: Other"
 /MN39Y    "Child given to drink: Not given anything to drink"
 /MN39NR   "Child given to drink: No response"
 /PN3U     "Duration of staying in the health facility - unit"
 /PN3N     "Duration of staying in the health facility - number"
 /PN4      "Baby's health checked before leaving health facility"
 /PN5      "Mother's health checked before leaving health facility"
 /PN6      "Baby's health checked after leaving health facility"
 /PN8      "Baby checked after the delivery was over"
 /PN9      "Mother checked after the delivery was over"
 /PN10     "Additional baby check after the delivery"
 /PN11     "Baby checked after the delivery"
 /PN12     "Number of times baby was checked"
 /PN13U    "How long after delivery did the first check of baby happen - unit"
 /PN13N    "How long after delivery did the first check of baby happen - number"
 /PN14A    "Person checking on baby's health: Doctor"
 /PN14B    "Person checking on baby's health: Nurse / Midwife"
 /PN14F    "Person checking on baby's health: Traditional birth attendant"
 /PN14H    "Person checking on baby's health: Relative / Friend"
 /PN14X    "Person checking on baby's health: Other"
 /PN14NR   "Person checking on baby's health: Missing"
 /PN15     "Place where baby's health was checked"
 /PN17     "Mother's health checked after leaving health facility"
 /PN19     "Mother's health checked after the delivery was over"
 /PN20     "Mother's health checked after the birth of the baby"
 /PN21     "Number of times mother's health was checked after the birth"
 /PN22U    "How long after delivery did the first check of mother happen - unit"
 /PN22N    "How long after delivery did the first check of mother happen - number"
 /PN23A    "Person checking on mother's health: Doctor"
 /PN23B    "Person checking on mother's health: Nurse / Midwife"
 /PN23F    "Person checking on mother's health: Traditional birth attendant"
 /PN23H    "Person checking on mother's health: Relative / Friend"
 /PN23X    "Person checking on mother's health: Other"
 /PN23NR   "Person checking on mother's health: Missing"
 /PN24     "Place where mother's health was checked"
 /PN25A    "During two days after birth health care provider: Examine cord"
 /PN25B    "During two days after birth health care provider: Take temperature"
 /PN25C    "During two days after birth health care provider: Counsel on breastfeeding"
 /PN27     "During two days after birth health care provider observe child's breastfeeding"
 /PN29     "During two days after birth health care provider weighter child again"
 /PN30     "During two days after birth health care provider gave informtion on symtomps"
 /CP1      "Currently pregnant"
 /CP2      "Currently using a method to avoid pregnancy"
 /CP3      "Ever used a method to avoid pregnancy"
 /CP4A     "Current method: Female sterilization / Tie-off"
 /CP4B     "Current method: Male sterilization / Vasectomy"
 /CP4C     "Current method: IUD"
 /CP4D     "Current method: Injectables / Injection"
 /CP4E     "Current method: Implants"
 /CP4F     "Current method: Pill"
 /CP4G     "Current method: Male condom"
 /CP4H     "Current method: Female condom"
 /CP4I     "Current method: Diaphragm"
 /CP4J     "Current method: Foam / Jelly"
 /CP4K     "Lactational amenorrhoea method (LAM)"
 /CP4L     "Current method: Periodic abstinence / Rhythm / Calendar"
 /CP4M     "Current method: Withdrawal"
 /CP4X     "Current method: Other"
 /CP4NR    "Current method: Missing"
 /UN2      "Wanted to get pregnant at the time"
 /UN4      "Wanted baby later or did not want more children"
 /UN5      "Would like to have another child (currently pregnant)"
 /UN7      "Would like to have another child (not currently pregnant)"
 /UN8U     "Desired waiting time (unit)"
 /UN8N     "Desired waiting time (number)"
 /UN11     "Able to get pregnant"
 /UN12A    "Reason: Infrequent sex / No sex"
 /UN12B    "Reason: Menopausal"
 /UN12C    "Reason: Never menstruated"
 /UN12D    "Reason: Hysterectomy"
 /UN12E    "Reason: Trying to get pregnant for 2 years without result"
 /UN12F    "Reason: Postpartum amenorrheic"
 /UN12G    "Reason: Breastfeeding"
 /UN12H    "Reason: Too old"
 /UN12I    "Reason: Fatalistic"
 /UN12X    "Reason: Other"
 /UN12Z    "Reason: Don't know"
 /UN12NR   "Reason: Missing"
 /UN14U    "Start of last menstrual period - unit"
 /UN14N    "Start of last menstrual period - number"
 /UN16     "Social activities, school or work days not attended due to menstruation"
 /UN17     "Availability of private place for washing during last menstrual period"
 /UN18     "Used any materials such as sanitary pads, tampons or cloth"
 /UN19     "Materials reusable"
 /DV1A     "If she goes out with out telling husband: wife beating justified"
 /DV1B     "If she neglects the children: wife beating justified"
 /DV1C     "If she argues with husband: wife beating justified"
 /DV1D     "If she refuses sex with husband: wife beating justified"
 /DV1E     "If she burns the food: wife beating justified"
 /VT1      "Something taken by using force or someone threatening to use force"
 /VT2      "Victimisation happened during the last 12 months"
 /VT3      "Number of times victimisation happened in the last year"
 /VT5      "The last time that this happened, was anything stolen"
 /VT6      "Person(s) had a weapon"
 /VT7A     "Offender(s) had a knife, a gun or something else used as a weapon: A knife"
 /VT7B     "Offender(s) had a knife, a gun or something else used as a weapon: A gun"
 /VT7X     "Offender(s) had a knife, a gun or something else used as a weapon: Other weapon"
 /VT7NR    "Offender(s) had a knife, a gun or something else used as a weapon: Missing"
 /VT8      "Incident reported to the police"
 /VT9      "Personally attacked or threatened by someone in really frightening way"
 /VT10     "Attack happened during the last 12 months"
 /VT11     "Number of times attack happened in the last year"
 /VT12     "Place attack happened the last time"
 /VT13     "Number of people involved in committing the offence"
 /VT14     "At least one of the offender(s) recognized at the time of the incident"
 /VT17     "Person(s) had a weapon"
 /VT18A    "Offender(s) had a knife, a gun or something else used as a weapon: A knife"
 /VT18B    "Offender(s) had a knife, a gun or something else used as a weapon: A gun"
 /VT18X    "Offender(s) had a knife, a gun or something else used as a weapon: Other weapon"
 /VT18NR   "Offender(s) had a knife, a gun or something else used as a weapon: Missing"
 /VT19     "Incident reported to the police"
 /VT20     "Feeling safe walking alone in neighbourhood after dark"
 /VT21     "Feeling safe at home alone after dark"
 /VT22A    "In the past 12 months, felt discriminated: Ethnic or immigration origin"
 /VT22B    "In the past 12 months, felt discriminated: Gender"
 /VT22C    "In the past 12 months, felt discriminated: Sexual orientation"
 /VT22D    "In the past 12 months, felt discriminated: Age"
 /VT22F    "In the past 12 months, felt discriminated: Disability"
 /VT22X    "In the past 12 months, felt discriminated: any other reason"
 /MA1      "Currently married or living with a man"
 /MA2      "Age of husband/partner"
 /MA5      "Ever married or lived with a man"
 /MA6      "Marital status"
 /MA7      "Married or lived with a man once or more than once"
 /MA8M     "Month of first union"
 /MA8Y     "Year of first union"
 /MA11     "Age at first union"
 /MA8C     "Date of first marriage of woman (CMC)"
 /MA8F     "Date flag for MA8"
 /MA11C    "Age at first marriage of respondent (calculated)"
 /AF2      "Use glasses or contact lenses"
 /AF3      "Use hearing aid"
 /AF6      "Difficulty seeing, even if wearing glasses or contact lenses"
 /AF8      "Difficulty hearing, even if using a hearing aid"
 /AF9      "Difficulty walking or climbing steps"
 /AF10     "Difficulty remembering or concentrating"
 /AF11     "Difficulty with self-care, such as washing all over or dressing"
 /AF12     "Difficulty communicating"
 /HA1      "Ever heard of HIV or AIDS"
 /HA2      "Can avoid HIV by having one uninfected partner"
 /HA3      "Can get HIV from mosquito bites"
 /HA4      "Can avoid HIV by using a condom correctly every time"
 /HA5      "Can get HIV by sharing food with a person who has HIV"
 /HA6      "Can get HIV through supernatural means"
 /HA7      "Healthy-looking person may have HIV"
 /HA8A     "HIV from mother to child during pregnancy"
 /HA8B     "HIV from mother to child during delivery"
 /HA8C     "HIV from mother to child through breastfeeding"
 /HA10     "Aware of drugs used to reduce the risk of transmission to the baby"
 /HA13A    "Given information about HIV during antenatal care visit: HIV from mother"
 /HA13B    "Given information about HIV during antenatal care visit: Things to do"
 /HA13C    "Given information about HIV during antenatal care visit: Tested for HIV"
 /HA13D    "Given information about HIV during antenatal care visit: Offered a test"
 /HA14     "Tested for HIV as part of antenatal care"
 /HA15     "Received results from test during antenatal care"
 /HA16     "Received consultation after testing during antenatal care"
 /HA18     "Offered test for HIV before delivery"
 /HA19     "Tested for HIV during delivery"
 /HA20     "Received results from test during delivery"
 /HA22     "Tested for HIV since test during pregnancy"
 /HA23     "Most recent time of testing for HIV"
 /HA24     "Ever been tested for HIV"
 /HA25     "Most recent time of testing for HIV"
 /HA26     "Received results of HIV test"
 /HA27     "Know a place to get HIV test"
 /HA28     "Heard of test kit for HIV testing"
 /HA29     "Ever tested yourself using test kit"
 /HA30     "Would buy fresh vegetables from shopkeeper with AIDS virus"
 /HA31     "Children living with HIV should be allowed to attend school with other children"
 /HA32     "People hesitate to take an HIV test because they are afraid of how other people will react if the test result is positive"
 /HA33     "People talk badly about people living with HIV, or who are thought to be living with HIV"
 /HA34     "People living with HIV, or thought to be living with HIV, lose the respect of other people"
 /HA35     "Agreement with the following statement: I would be ashamed if someone in my family had HIV"
 /HA36     "Fear of getting HIV in contact with the saliva of a person living with HIV"
 /TA1      "Ever tried cigarette smoking"
 /TA2      "Age when cigarette was smoked for the first time"
 /TA3      "Currently smoking cigarettes"
 /TA4      "Number of cigarettes smoked in the last 24 hours"
 /TA5      "Number of days when cigarettes were smoked in past month"
 /TA6      "Ever tried any smoked tobacco products other than cigarettes"
 /TA7      "Used any smoked tobacco products during the last month"
 /TA8A     "Type of smoked tobacco product: Cigars"
 /TA8B     "Type of smoked tobacco product: Water pipe"
 /TA8C     "Type of smoked tobacco product: Cigarillos"
 /TA8D     "Type of smoked tobacco product: Pipe"
 /TA8X     "Type of smoked tobacco product: Other"
 /TA8NR    "Type of smoked tobacco product: No response"
 /TA9      "Number of days when tobacco products where smoked in past month"
 /TA10     "Ever tried any form of smokeless tobacco products"
 /TA11     "Used any smokeless tobacco products during the last month"
 /TA12B    "Type of smokeless tobacco product used: Chewing tobacco"
 /TA12X    "Type of smokeless tobacco product used: Other"
 /TA12NR   "Type of smokeless tobacco product used: No response"
 /TA13     "Number of days when smokeless tobacco products where used in past month"
 /TA14     "Ever drunk alcohol"
 /TA15     "Age when alcohol was used for the first time"
 /TA16     "Number of days when at least one drink of alcohol was used in past month"
 /TA17     "Number of drinks usually consumed"
 /HH4      "Supervisor number"
 /HH6      "Area"
 /HH7      "Region"
 /WDOB     "Date of birth of woman (CMC)"
 /WDOM     "Date of marriage (CMC)"
 /WAGEM    "Age at first marriage/union"
 /WDOBFC   "Date of birth of first child (CMC)"
 /WDOBLC   "Date of birth of last child (CMC)"
 /SEXLASTC "Sexe du dernier né"
 /MSTATUS  "Marital/Union status"
 /CEB      "Children ever born"
 /CSURV    "Children surviving"
 /CDEAD    "Children dead"
.
VALUE LABELS
  WM8     
     1 "YES, INTERVIEWED ALREADY"
     2 "NO, FIRST INTERVIEW"
 /WM9     
     1 "YES, PERMISSION IS GIVEN"
     2 "NO, PERMISSION IS NOT GIVEN"
 /WM17    
     1 "COMPLETED"
     2 "NOT AT HOME"
     3 "REFUSED"
     4 "PARTLY COMPLETED"
     5 "INCAPACITATED"
     6 "NO ADULT CONSENT FOR RESPONDENT AGE 15-17"
    96 "OTHER"
 /WM11    
     1 "YES, THE ENTIRE INTERVIEW WAS COMPLETED IN PRIVATE"
     2 "NO, OTHERS WERE PRESENT DURING THE ENTIRE INTERVIEW"
     3 "NO, OTHERS WERE PRESENT DURING PART OF THE INTERVIEW"
 /WM12    
     1 "ARABIC"
     2 "FRANCAIS"
 /WM13    
     1 "ARABIC"
     2 "FRENCH"
     6 "OTHER LANGUAGE"
 /WM14    
     1 "ARAB"
     2 "FRENCH"
     6 "OTHER LANGUAGE"
 /WM15    
     1 "YES, THE ENTIRE QUESTIONNAIRE"
     2 "YES, PARTS OF THE QUESTIONNAIRE"
     3 "NO, NOT USED"
 /WB3M    
     1 "JANUARY"
     2 "FEBRUARY"
     3 "MARCH"
     4 "APRIL"
     5 "MAY"
     6 "JUNE"
     7 "JULY"
     8 "AUGUST"
     9 "SEPTEMBER"
    10 "OCTOBER"
    11 "NOVEMBER"
    12 "DECEMBER"
    98 "DK"
    99 "NO RESPONSE"
 /WB3Y    
  9998 "DK"
  9999 "NO RESPONSE"
 /WB5     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /WB6A    
     0 "ECE"
     1 "PRIMARY"
     2 "LOWER SECONDARY"
     3 "UPPER SECONDARY"
     4 "HIGHER"
     5 "ADULT EDUCATION"
     8 "DK"
     9 "NO RESPONSE"
 /WB6B    
    97 "INCONSISTENT"
    98 "DK"
    99 "NO RESPONSE"
 /WB7     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /WB9     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /WB10A   
     1 "PRIMARY"
     2 "LOWER SECONDARY"
     3 "UPPER SECONDARY"
     4 "HIGHER"
     5 "VOCATIONAL TRAINING SCHOOL"
     6 "CAP "
     7 "BTP"
     8 "BTS"
     9 "VOCATIONAL TRAINING"
    10 "ADULT EDUCATION"
    98 "DK"
    99 "NO RESPONSE"
 /WB10B   
    97 "INCONSISTENT"
    98 "DK"
    99 "NO RESPONSE"
 /WB11    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /WB12A   
     1 "PRIMARY"
     2 "LOWER SECONDARY"
     3 "UPPER SECONDARY"
     4 "HIGHER"
     5 "VOCATIONAL TRAINING SCHOOL"
     6 "CAP "
     7 "BTP"
     8 "BTS"
     9 "VOCATIONAL TRAINING"
    10 "ADULT EDUCATION"
    98 "DK"
    99 "NO RESPONSE"
 /WB12B   
    97 "INCONSISTENT"
    98 "DK"
    99 "NO RESPONSE"
 /WB14    
     1 "CANNOT READ AT ALL"
     2 "ABLE TO READ ONLY PARTS OF SENTENCE"
     3 "ABLE TO READ WHOLE SENTENCE"
     4 "PAS DE PHRASE DANS LA LANGUE REQUISE"
     9 "NO RESPONSE"
 /WB15    
    95 "ALWAYS / SINCE BIRTH"
    98 "DK"
    99 "NO RESPONSE"
 /WB16    
     1 "CITY"
     3 "RURAL AREA"
     9 "NO RESPONSE"
 /WB17    
     1 "DISTRICT TUNIS"
     2 "NORD EST"
     3 "NORD OUEST"
     4 "CENTRE EST"
     5 "CENTRE OUEST"
     6 "SUD EST"
     7 "SUD OUEST"
    96 "OUTSIDE OF COUNTRY"
    99 "NO RESPONSE"
 /WB18    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /WB19A   
  'A' "MUTUAL HEALTH ORGANIZATION / COMMUNITY-BASED HEALTH INSURANCE"
  '?' "NO RESPONSE"
 /WB19D   
  'D' "OTHER PRIVATELY PURCHASED COMMERCIAL HEALTH INSURANCE"
  '?' "NO RESPONSE"
 /WB19E   
  'E' "HEALTH INSURANCE THROUGH EMPLOYER"
  '?' "NO RESPONSE"
 /WB19F   
  'F' "SOCIAL SECURITY"
  '?' "NO RESPONSE"
 /WB19X   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /WB19NR  
  '?' "NO RESPONSE"
 /WB3F    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
 /WAGE    
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
 /MT1     
     0 "NOT AT ALL"
     1 "LESS THAN ONCE A WEEK"
     2 "AT LEAST ONCE A WEEK"
     3 "ALMOST EVERY DAY"
     9 "NO RESPONSE"
 /MT2     
     0 "NOT AT ALL"
     1 "LESS THAN ONCE A WEEK"
     2 "AT LEAST ONCE A WEEK"
     3 "ALMOST EVERY DAY"
     9 "NO RESPONSE"
 /MT3     
     0 "NOT AT ALL"
     1 "LESS THAN ONCE A WEEK"
     2 "AT LEAST ONCE A WEEK"
     3 "ALMOST EVERY DAY"
     9 "NO RESPONSE"
 /MT4     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MT5     
     0 "NOT AT ALL"
     1 "LESS THAN ONCE A WEEK"
     2 "AT LEAST ONCE A WEEK"
     3 "ALMOST EVERY DAY"
     9 "NO RESPONSE"
 /MT6A    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MT6B    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MT6C    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MT6D    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MT6E    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MT6F    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MT6G    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MT6H    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MT6I    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MT9     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MT10    
     0 "NOT AT ALL"
     1 "LESS THAN ONCE A WEEK"
     2 "AT LEAST ONCE A WEEK"
     3 "ALMOST EVERY DAY"
     9 "NO RESPONSE"
 /MT11    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MT12    
     0 "NOT AT ALL"
     1 "LESS THAN ONCE A WEEK"
     2 "AT LEAST ONCE A WEEK"
     3 "ALMOST EVERY DAY"
     9 "NO RESPONSE"
 /CM1     
     1 "YES"
     2 "NO"
 /CM2     
     1 "YES"
     2 "NO"
 /CM5     
     1 "YES"
     2 "NO"
 /CM8     
     1 "YES"
     2 "NO"
 /CM12    
     1 "YES"
     2 "NO"
 /CM15    
     1 "NUMBERS ARE THE SAME"
     2 "NUMBERS ARE DIFFERENT"
 /CM17    
     0 "NO LIVE BIRTHS IN THE LAST 2 YEARS"
     1 "ONE OR MORE LIVE BIRTHS IN THE LAST 2 YEARS"
 /BH11    
     1 "YES"
     2 "NO"
 /DB2     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /DB4     
     1 "LATER"
     2 "NO MORE"
     9 "NO RESPONSE"
 /MN2     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MN3A    
  'A' "DOCTOR"
  '?' "NO RESPONSE"
 /MN3B    
  'B' "NURSE / MIDWIFE"
  '?' "NO RESPONSE"
 /MN3F    
  'F' "TRADITIONAL BIRTH ATTENDANT"
  '?' "NO RESPONSE"
 /MN3X    
  'X' "OTHER"
  '?' "NO RESPONSE"
 /MN4AU   
     1 "WEEKS"
     2 "MONTHS"
     9 "SPECIAL"
 /MN4AN   
    98 "DK"
    99 "NO RESPONSE"
 /MN5     
    98 "DK"
    99 "NO RESPONSE"
 /MN6A    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MN6B    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MN6C    
     1 "YES"
     2 "NO"
     9 "NO REPONSE"
 /MN8     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /MN9     
     8 "DK"
     9 "NO RESPONSE"
 /MN11    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /MN12    
     7 "7+"
     8 "DK"
     9 "NO RESPONSE"
 /MN14    
    98 "DK"
    99 "NO RESPONSE"
 /MN19A   
  'A' "DOCTOR"
  '?' "NO RESPONSE"
 /MN19B   
  'B' "NURSE / MIDWIFE"
  '?' "NO RESPONSE"
 /MN19F   
  'F' "TRADITIONAL BIRTH ATTENDANT"
  '?' "NO RESPONSE"
 /MN19H   
  'H' "RELATIVE / FRIEND"
  '?' "NO RESPONSE"
 /MN19X   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /MN19Y   
  'Y' "NO ONE"
  '?' "NO RESPONSE"
 /MN19NR  
  '?' "NO RESPONSE"
 /MN20    
    11 "RESPONDENT'S HOME"
    12 "OTHER HOME"
    21 "GOVERNMENT HOSPITAL"
    22 "GOVERNMENT CLINIC / HEALTH CENTRE"
    26 "OTHER PUBLIC"
    31 "PRIVATE HOSPITAL"
    32 "PRIVATE CLINIC"
    36 "OTHER PRIVATE MEDICAL"
    96 "OTHER"
    99 "NO RESPONSE"
 /MN21    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MN22    
     1 "BEFORE LABOUR PAINS"
     2 "AFTER LABOUR PAINS"
     9 "NO RESPONSE"
 /MN23    
     1 "YES"
     2 "NO"
     8 "DK/ DON’T REMEMBER"
     9 "NO RESPONSE"
 /MN24    
     1 "YES"
     2 "NO"
     8 "DK/ DON’T REMEMBER"
     9 "NO RESPONSE"
 /MN25    
     1 "YES"
     2 "NO"
     8 "DK/ DON’T REMEMBER"
     9 "NO RESPONSE"
 /MN26U   
     0 "IMMEDIATELY"
     1 "HOURS"
     2 "DAYS"
     9 "SPECIAL"
 /MN26N   
     0 "IMMEDIATELY"
    97 "NO BATH"
    98 "DK / DON’T REMEMBER"
    99 "NO RESPONSE"
 /MN28    
     1 "NEW BLADE"
     2 "BLADE USED FOR OTHER PURPOSES"
     3 "SCISSORS"
     6 "OTHER"
     8 "DK"
     9 "NO RESPONSE"
 /MN29    
     1 "YES"
     2 "NO"
     8 "DK / DON’T REMEMBER"
     9 "NO RESPONSE"
 /MN30    
     1 "YES"
     2 "NO"
     8 "DK / DON’T REMEMBER"
     9 "NO RESPONSE"
 /MN31A   
  'A' "CHLORHEXIDINE"
  '?' "NO RESPONSE"
 /MN31B   
  'B' "OTHER ANTISEPTIC (ALCOHOL, SPIRIT, GENTIAN VIOLET)"
  '?' "NO RESPONSE"
 /MN31X   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /MN31Z   
  'Z' "DK / DON’T REMEMBER"
  '?' "NO RESPONSE"
 /MN31NR  
  '?' "NO RESPONSE"
 /MN32    
     1 "VERY LARGE"
     2 "LARGER THAN AVERAGE"
     3 "AVERAGE"
     4 "SMALLER THAN AVERAGE"
     5 "VERY SMALL"
     8 "DK"
     9 "NO RESPONSE"
 /MN33    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /MN34A   
     1 "FROM CARD"
     2 "FROM RECALL"
     9 "SPECIAL"
 /MN34    
  9,998 "DK"
  9,999 "NO RESPONSE"
 /MN35    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MN36    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MN37U   
     0 "IMMEDIATELY"
     1 "HOURS"
     2 "DAYS"
     9 "SPECIAL"
 /MN37N   
     0 "IMMEDIATELY"
    98 "DK / DON’T REMEMBER"
    99 "NO RESPONSE"
 /MN38    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /MN39A   
  'A' "MILK (OTHER THAN BREAST MILK)"
  '?' "NO RESPONSE"
 /MN39B   
  'B' "PLAIN WATER"
  '?' "NO RESPONSE"
 /MN39C   
  'C' "SUGAR OR GLUCOSE WATER"
  '?' "NO RESPONSE"
 /MN39D   
  'D' "GRIPE WATER"
  '?' "NO RESPONSE"
 /MN39E   
  'E' "SUGAR-SALT-WATER SOLUTION"
  '?' "NO RESPONSE"
 /MN39F   
  'F' "FRUIT JUICE"
  '?' "NO RESPONSE"
 /MN39G   
  'G' "INFANT FORMULA"
  '?' "NO RESPONSE"
 /MN39H   
  'H' "TEA / INFUSIONS / TRADITIONAL HERBAL PREPARATIONS"
  '?' "NO RESPONSE"
 /MN39I   
  'I' "HONEY"
  '?' "NO RESPONSE"
 /MN39J   
  'J' "PRESCRIBED MEDICINE"
  '?' "NO RESPONSE"
 /MN39X   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /MN39Y   
  'Y' "NOT GIVEN ANYTHING TO DRINK"
  '?' "NO RESPONSE"
 /MN39NR  
  '?' "NO RESPONSE"
 /PN3U    
     1 "HOURS"
     2 "DAYS"
     3 "WEEKS"
     9 "SPECIAL"
 /PN3N    
    98 "DK / DON’T REMEMBER"
    99 "NO RESPONSE"
 /PN4     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /PN5     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /PN6     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /PN8     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /PN9     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /PN10    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /PN11    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /PN12    
     1 "ONCE"
     2 "MORE THAN ONCE"
     9 "NO RESPONSE"
 /PN13U   
     1 "HOURS"
     2 "DAYS"
     3 "WEEKS"
     9 "SPECIAL"
 /PN13N   
    98 "DK / DON’T REMEMBER"
    99 "NO RESPONSE"
 /PN14A   
  'A' "DOCTOR"
  '?' "NO RESPONSE"
 /PN14B   
  'B' "NURSE / MIDWIFE"
  '?' "NO RESPONSE"
 /PN14F   
  'F' "TRADITIONAL BIRTH ATTENDANT"
  '?' "NO RESPONSE"
 /PN14H   
  'H' "RELATIVE / FRIEND"
  '?' "NO RESPONSE"
 /PN14X   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /PN14NR  
  '?' "NO RESPONSE"
 /PN15    
    11 "RESPONDENT'S HOME"
    12 "OTHER HOME"
    21 "GOVERNMENT HOSPITAL"
    22 "GOVERNMENT CLINIC / HEALTH CENTRE"
    26 "OTHER PUBLIC"
    31 "PRIVATE HOSPITAL"
    32 "PRIVATE CLINIC"
    96 "OTHER PRIVATE MEDICAL"
    99 "NO RESPONSE"
 /PN17    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /PN19    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /PN20    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /PN21    
     1 "ONCE"
     2 "MORE THAN ONCE"
     9 "NO RESPONSE"
 /PN22U   
     1 "HOURS"
     2 "DAYS"
     3 "WEEKS"
     9 "SPECIAL"
 /PN22N   
    98 "DK / DON’T REMEMBER"
    99 "NO RESPONSE"
 /PN23A   
  'A' "DOCTOR"
  '?' "NO RESPONSE"
 /PN23B   
  'B' "NURSE / MIDWIFE"
  '?' "NO RESPONSE"
 /PN23F   
  'F' "TRADITIONAL BIRTH ATTENDANT"
  '?' "NO RESPONSE"
 /PN23H   
  'H' "RELATIVE / FRIEND"
  '?' "NO RESPONSE"
 /PN23X   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /PN23NR  
  '?' "NO RESPONSE"
 /PN24    
    11 "RESPONDENT'S HOME"
    12 "OTHER HOME"
    21 "GOVERNMENT HOSPITAL"
    22 "GOVERNMENT CLINIC / HEALTH CENTRE"
    26 "OTHER PUBLIC"
    31 "PRIVATE HOSPITAL"
    32 "PRIVATE CLINIC"
    96 "OTHER"
    99 "NO RESPONSE"
 /PN25A   
     1 "YES"
     2 "NO"
     8 "NS"
     9 "NO RESPONSE"
 /PN25B   
     1 "YES"
     2 "NO"
     8 "NS"
     9 "NO RESPONSE"
 /PN25C   
     1 "YES"
     2 "NO"
     8 "NS"
     9 "NO RESPONSE"
 /PN27    
     1 "YES"
     2 "NO"
     8 "NS"
     9 "NO RESPONSE"
 /PN29    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /PN30    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /CP1     
     1 "YES, CURRENTLY PREGNANT"
     2 "NO"
     8 "DK OR NOT SURE"
     9 "NO RESPONSE"
 /CP2     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /CP3     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /CP4A    
  'A' "FEMALE STERILIZATION"
  '?' "NO RESPONSE"
 /CP4B    
  'B' "MALE STERILIZATION"
  '?' "NO RESPONSE"
 /CP4C    
  'C' "IUD"
  '?' "NO RESPONSE"
 /CP4D    
  'D' "INJECTABLES"
  '?' "NO RESPONSE"
 /CP4E    
  'E' "IMPLANTS"
  '?' "NO RESPONSE"
 /CP4F    
  'F' "PILL"
  '?' "NO RESPONSE"
 /CP4G    
  'G' "MALE CONDOM"
  '?' "NO RESPONSE"
 /CP4H    
  'H' "FEMALE CONDOM"
  '?' "NO RESPONSE"
 /CP4I    
  'I' "DIAPHRAGM"
  '?' "NO RESPONSE"
 /CP4J    
  'J' "FOAM / JELLY"
  '?' "NO RESPONSE"
 /CP4K    
  'K' "LACTATIONAL AMENORRHOEA METHOD (LAM)"
  '?' "NO RESPONSE"
 /CP4L    
  'L' "PERIODIC ABSTINENCE / RHYTHM"
  '?' "NO RESPONSE"
 /CP4M    
  'M' "WITHDRAWAL"
  '?' "NO RESPONSE"
 /CP4X    
  'X' "OTHER"
  '?' "NO RESPONSE"
 /CP4NR   
  '?' "NO RESPONSE"
 /UN2     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /UN4     
     1 "LATER"
     2 "NONE / NO MORE"
     9 "NO RESPONSE"
 /UN5     
     1 "HAVE ANOTHER CHILD"
     2 "NO MORE / NONE"
     8 "UNDECIDED / DK"
     9 "NO RESPONSE"
 /UN7     
     1 "HAVE (A/ANOTHER) CHILD"
     2 "NO MORE / NONE"
     3 "SAYS SHE CANNOT GET PREGNANT"
     8 "UNDECIDED / DK"
     9 "NO RESPONSE"
 /UN8U    
     1 "MONTHS"
     2 "YEARS"
     9 "SPECIAL"
 /UN8N    
    93 "DOES NOT WANT TO WAIT (SOON/NOW)"
    94 "SAYS SHE CANNOT GET PREGNANT"
    95 "AFTER MARRIAGE"
    96 "OTHER"
    98 "DK"
    99 "NO RESPONSE"
 /UN11    
     1 "Yes"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /UN12A   
  'A' "INFREQUENT SEX / NO SEX"
  '?' "NO RESPONSE"
 /UN12B   
  'B' "MENOPAUSAL"
  '?' "NO RESPONSE"
 /UN12C   
  'C' "NEVER MENSTRUATED"
  '?' "NO RESPONSE"
 /UN12D   
  'D' "HYSTERECTOMY (SURGICAL REMOVAL OF UTERUS)"
  '?' "NO RESPONSE"
 /UN12E   
  'E' "HAS BEEN TRYING TO GET PREGNANT FOR 2 YEARS OR MORE WITHOUT RESULT"
  '?' "NO RESPONSE"
 /UN12F   
  'F' "POSTPARTUM AMENORRHEIC"
  '?' "NO RESPONSE"
 /UN12G   
  'G' "BREASTFEEDING"
  '?' "NO RESPONSE"
 /UN12H   
  'H' "TOO OLD"
  '?' "NO RESPONSE"
 /UN12I   
  'I' "FATALISTIC"
  '?' "NO RESPONSE"
 /UN12X   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /UN12Z   
  'Z' "DK"
  '?' "NO RESPONSE"
 /UN12NR  
  '?' "NO RESPONSE"
 /UN14U   
     1 "DAYS AGO"
     2 "WEEKS AGO"
     3 "MONTHS AGO"
     4 "YEARS AGO"
     9 "SPECIAL"
 /UN14N   
    93 "IN MENOPAUSE / HAS HAD HYSTERECTOMY"
    94 "BEFORE LAST BIRTH"
    95 "NEVER MENSTRUATED"
    99 "NO RESPONSE"
 /UN16    
     1 "YES"
     2 "NO"
     8 "DK / NOT SURE / NO SUCH ACTIVITY"
     9 "NO RESPONSE"
 /UN17    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /UN18    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /UN19    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /DV1A    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /DV1B    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /DV1C    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /DV1D    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /DV1E    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /VT1     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /VT2     
     1 "YES, DURING THE LAST 12 MONTHS"
     2 "NO, MORE THAN 12 MONTHS AGO"
     8 "DK / DON’T REMEMBER"
     9 "NO RESPONSE"
 /VT3     
     1 "ONE TIME"
     2 "TWO TIMES"
     3 "THREE OR MORE TIMES"
     8 "DK / DON’T REMEMBER"
     9 "NO RESPONSE"
 /VT5     
     1 "YES"
     2 "NO"
     8 "DK / NOT SURE"
     9 "NO RESPONSE"
 /VT6     
     1 "YES"
     2 "NO"
     8 "DK / NOT SURE"
     9 "NO RESPONSE"
 /VT7A    
  'A' "YES, A KNIFE"
  '?' "NO RESPONSE"
 /VT7B    
  'B' "YES, A GUN"
  '?' "NO RESPONSE"
 /VT7X    
  'X' "YES, SOMETHING ELSE"
  '?' "NO RESPONSE"
 /VT7NR   
  '?' "NO RESPONSE"
 /VT8     
     1 "YES, RESPONDENT REPORTED"
     2 "YES, SOMEONE ELSE REPORTED"
     3 "NO, NOT REPORTED"
     8 "DK / NOT SURE"
     9 "NO RESPONSE"
 /VT9     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /VT10    
     1 "YES, DURING THE LAST 12 MONTHS"
     2 "NO, MORE THAN 12 MONTHS AGO"
     8 "DK / DON’T REMEMBER"
     9 "NO RESPONSE"
 /VT11    
     1 "ONE TIME"
     2 "TWO TIMES"
     3 "THREE OR MORE TIMES"
     8 "DK / DON’T REMEMBER"
     9 "NO RESPONSE"
 /VT12    
    11 "AT HOME"
    12 "IN ANOTHER HOME"
    21 "IN THE STREET"
    22 "ON PUBLIC TRANSPORT"
    23 "PUBLIC RESTAURANT / CAFÉ / BAR"
    26 "OTHER PUBLIC"
    31 "AT SCHOOL"
    32 "AT WORKPLACE"
    96 "OTHER PLACE"
    99 "NO RESPONSE"
 /VT13    
     1 "ONE PERSON"
     2 "TWO PEOPLE"
     3 "THREE OR MORE PEOPLE"
     8 "DK / DON’T REMEMBER"
     9 "NO RESPONSE"
 /VT14    
     1 "YES"
     2 "NO"
     8 "DK / DON’T REMEMBER"
     9 "NO RESPONSE"
 /VT17    
     1 "YES"
     2 "NO"
     8 "DK / NOT SURE"
     9 "NO RESPONSE"
 /VT18A   
  'A' "YES, A KNIFE"
  '?' "NO RESPONSE"
 /VT18B   
  'B' "YES, A GUN"
  '?' "NO RESPONSE"
 /VT18X   
  'X' "YES, SOMETHING ELSE"
  '?' "NO RESPONSE"
 /VT18NR  
  '?' "NO RESPONSE"
 /VT19    
     1 "YES, RESPONDENT REPORTED"
     2 "YES, SOMEONE ELSE REPORTED"
     3 "NO, NOT REPORTED"
     8 "DK / NOT SURE"
     9 "NO RESPONSE"
 /VT20    
     1 "VERY SAFE"
     2 "SAFE"
     3 "UNSAFE"
     4 "VERY UNSAFE"
     7 "NEVER WALK ALONE AFTER DARK"
     9 "NO RESPONSE"
 /VT21    
     1 "VERY SAFE"
     2 "SAFE"
     3 "UNSAFE"
     4 "VERY UNSAFE"
     7 "NEVER WALK ALONE AFTER DARK"
     9 "NO RESPONSE"
 /VT22A   
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /VT22B   
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /VT22C   
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /VT22D   
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /VT22F   
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /VT22X   
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /MA1     
     1 "YES, CURRENTLY MARRIED"
     3 "NO, NOT IN UNION"
     9 "NO RESPONSE"
 /MA2     
    98 "DK"
    99 "NO RESPONSE"
 /MA5     
     1 "YES, FORMERLY MARRIED"
     3 "NO"
     9 "NO RESPONSE"
 /MA6     
     1 "WIDOWED"
     2 "DIVORCED"
     3 "SEPARATED"
 /MA7     
     1 "ONLY ONCE"
     2 "MORE THAN ONCE"
     9 "NO RESPONSE"
 /MA8M    
     1 "JANUARY"
     2 "FEBRUARY"
     3 "MARCH"
     4 "APRIL"
     5 "MAY"
     6 "JUNE"
     7 "JULY"
     8 "AUGUST"
     9 "SEPTEMBER"
    10 "OCTOBER"
    11 "NOVEMBER"
    12 "DECEMBER"
    97 "INCONSISTENT"
    98 "DK"
    99 "NO RESPONSE"
 /MA8Y    
  9997 "INCONSISTENT"
  9998 "DK"
  9999 "NO RESPONSE"
 /MA11    
    97 "INCONSISTENT"
    98 "DK"
    99 "NO RESPONSE"
 /MA8F    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
 /AF2     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /AF3     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /AF6     
     1 "NO DIFFICULTY"
     2 "SOME DIFFICULTY"
     3 "A LOT OF DIFFICULTY"
     4 "CANNOT SEE AT ALL"
     9 "NO RESPONSE"
 /AF8     
     1 "NO DIFFICULTY"
     2 "SOME DIFFICULTY"
     3 "A LOT OF DIFFICULTY"
     4 "CANNOT SEE AT ALL"
     9 "NO RESPONSE"
 /AF9     
     1 "NO DIFFICULTY"
     2 "SOME DIFFICULTY"
     3 "A LOT OF DIFFICULTY"
     4 "CANNOT SEE AT ALL"
     9 "NO RESPONSE"
 /AF10    
     1 "NO DIFFICULTY"
     2 "SOME DIFFICULTY"
     3 "A LOT OF DIFFICULTY"
     4 "CANNOT SEE AT ALL"
     9 "NO RESPONSE"
 /AF11    
     1 "NO DIFFICULTY"
     2 "SOME DIFFICULTY"
     3 "A LOT OF DIFFICULTY"
     4 "CANNOT SEE AT ALL"
     9 "NO RESPONSE"
 /AF12    
     1 "NO DIFFICULTY"
     2 "SOME DIFFICULTY"
     3 "A LOT OF DIFFICULTY"
     9 "NO RESPONSE"
 /HA1     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /HA2     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA3     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA4     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA5     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA6     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA7     
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA8A    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA8B    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA8C    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA10    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA13A   
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA13B   
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA13C   
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA13D   
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA14    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA15    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA16    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA18    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /HA19    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA20    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /HA22    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /HA23    
     1 "LESS THAN 12 MONTHS AGO"
     2 "12-23 MONTHS AGO"
     3 "2 OR MORE YEARS AGO"
     9 "NO RESPONSE"
 /HA24    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /HA25    
     1 "LESS THAN 12 MONTHS AGO"
     2 "12-23 MONTHS AGO"
     3 "2 OR MORE YEARS AGO"
     9 "NO RESPONSE"
 /HA26    
     1 "YES"
     2 "NO"
     8 "DK"
     9 "NO RESPONSE"
 /HA27    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /HA28    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /HA29    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /HA30    
     1 "YES"
     2 "NO"
     8 "DK / NOT SURE / DEPENDS"
     9 "NO RESPONSE"
 /HA31    
     1 "YES"
     2 "NO"
     8 "DK / NOT SURE / DEPENDS"
     9 "NO RESPONSE"
 /HA32    
     1 "YES"
     2 "NO"
     8 "DK / NOT SURE / DEPENDS"
     9 "NO RESPONSE"
 /HA33    
     1 "YES"
     2 "NO"
     8 "DK / NOT SURE / DEPENDS"
     9 "NO RESPONSE"
 /HA34    
     1 "YES"
     2 "NO"
     8 "DK / NOT SURE / DEPENDS"
     9 "NO RESPONSE"
 /HA35    
     1 "AGREE"
     2 "DISAGREE"
     8 "DK / NOT SURE / DEPENDS"
     9 "NO RESPONSE"
 /HA36    
     1 "YES"
     2 "NO"
     7 "SAYS SHE HAS HIV"
     8 "DK / NOT SURE / DEPENDS"
     9 "NO RESPONSE"
 /TA1     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /TA2     
     0 "NEVER SMOKED A WHOLE CIGARETTE"
    99 "NO RESPONSE"
 /TA3     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /TA4     
    99 "NO RESPONSE"
 /TA5     
    10 "10 DAYS OR MORE BUT LESS THAN A MONTH"
    30 "EVERY DAY / ALMOST EVERY DAY"
    99 "NO RESPONSE"
 /TA6     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /TA7     
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /TA8A    
  'A' "CIGARS"
  '?' "NO RESPONSE"
 /TA8B    
  'B' "WATER PIPE"
  '?' "NO RESPONSE"
 /TA8C    
  'C' "CIGARILLOS"
  '?' "NO RESPONSE"
 /TA8D    
  'D' "PIPE"
  '?' "NO RESPONSE"
 /TA8X    
  'X' "OTHER"
  '?' "NO RESPONSE"
 /TA8NR   
  '?' "NO RESPONSE"
 /TA9     
    10 "10 DAYS OR MORE BUT LESS THAN A MONTH"
    30 "EVERY DAY / ALMOST EVERY DAY"
    99 "NO RESPONSE"
 /TA10    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /TA11    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /TA12B   
  'A' "CHEWING TOBACCO"
  '?' "NO RESPONSE"
 /TA12X   
  'X' "OTHER"
  '?' "NO RESPONSE"
 /TA12NR  
  '?' "NO RESPONSE"
 /TA13    
    10 "10 DAYS OR MORE BUT LESS THAN A MONTH"
    30 "EVERY DAY / ALMOST EVERY DAY"
    99 "NO RESPONSE"
 /TA14    
     1 "YES"
     2 "NO"
     9 "NO RESPONSE"
 /TA15    
     0 "NEVER HAD ONE DRINK OF ALCOHOL"
    99 "NO RESPONSE"
 /TA16    
     0 "DID NOT HAVE ONE DRINK IN LAST ONE MONTH"
    10 "10 DAYS OR MORE BUT LESS THAN A MONTH"
    30 "EVERY DAY / ALMOST EVERY DAY"
    99 "NO RESPONSE"
 /TA17    
    99 "NO RESPONSE"
 /HH6     
     1 "URBAIN"
     2 "RURAL"
 /HH7     
     1 "DISTRICT TUNIS"
     2 "NORD EST"
     3 "NORD OUEST"
     4 "CENTRE EST"
     5 "CENTRE OUEST"
     6 "SUD EST"
     7 "SUD OUEST"
 /SEXLASTC
     1 "Masculin"
     2 "Féminin"
 /MSTATUS 
     1 "Currently married/in union"
     2 "Formerly married/in union"
     3 "Never married/in union"
     9 "Missing"
.
EXECUTE.
