---
title: "Chapter 10 - WS 1.4 - WS 4.2"
output: github_document
always_allow_html: true
---


# Load libraries



```{r, warning = F, message = F}

library(tidyverse); library(haven); library(lubridate);
library(knitr); library(kableExtra);
library(Hmisc); library(survey)
library(expss); library(here); library(gmodels)
library(flextable); library(formattable)
library(prettydoc); library(officer)

library(tableone); library(sjPlot); 

```


# WS 1.4



Merge the person collecting the water with the household file. 

```{r}



hl <- read_sav(here("Data/Tunisia_hl.sav")) %>% arrange(HH1, HH2, HL1)

hh <- read_sav(here("Data/Tunisia_hh.sav")) %>% arrange(HH1, HH2)


hl <- hl %>% 
  mutate(elevel = ifelse(ED5A == 1, 1,
                         ifelse(ED5A == 2, 2,
                                ifelse(ED5A %in% 3:4, 3,
                                       ifelse(ED5A %in% 8:9, 9, 0)))))

var_lab(hl$elevel) = "Education"
val_lab(hl$elevel) = make_labels("
  0 None/ECE
  1 Primary
  2 Lower secondary
  3 Upper secondary or higher  
  9 DK/Missing                                
                       
                                 ")
  
  

tmp.person.cwater = hl %>% select(HH1, HH2, HL1, HL4, HL6, elevel) %>% rename(WS5 = HL1)



hh = hh %>% left_join(tmp.person.cwater, by = c("HH1", "HH2", "WS5")) %>% 
  filter(HH46 == 1, WS4 > 0) %>% 
  mutate(hhweightHH48 = HH48 * hhweight) %>%
  mutate(nhhmem = hhweightHH48)


var_lab(hh$nhhmem) = "Number of household members without drinking water on premises and where household members are primarily responsible for collecting water"


hh <- hh %>% 
  mutate(Time = NA) %>% 
  mutate(Time = ifelse(WS4 < 995 & WS6 < 95, floor(WS4 * WS6 / 7), Time)) %>% 
  mutate(Time = ifelse(Time %in% 0:30, 1,
                       ifelse(Time %in% 31:60, 2,
                              ifelse(Time %in% 61:180, 3,
                                     ifelse(Time >= 181, 4, Time)))))

hh <- hh %>% mutate(averagetime = Time) %>% 
  mutate(averagetime = ifelse(WS4 > 995 | WS6 > 95, 9, averagetime))


hh <- hh %>% mutate(age1 = ifelse(HL6 %in% 0:14, 1,
                                  ifelse(HL6 %in% 15:49, 3,
                                         ifelse(HL6 %in% 50:95, 4, 9)))) # age age1



hh = hh %>% mutate(age2 = ifelse(HL6 %in% 15:17, 2, NA))

var_lab(hh$age1) = "Age"; var_lab(hh$age2) = "Age"





val_lab(hh$age1) = make_labels("
1 <15
2 15-17
3 15-49
4 50+
             ")
val_lab(hh$age2) = make_labels("

2 15-49


             ")

val_lab(hh$averagetime) = make_labels("
    1 Up to 30 minutes
    2 From 31 mins to 1 hour
    3 Over 1 hour to 3 hours
    4 Over 3 hours
    9 DK/Missing
                                      ")



source(here("R/drinkingWater.R"))


hh$nn = 1

```




Table functions successful!

## SFR 1.4

```{r}






row.vars = list(total(), hh$HH6, hh$HH7, hh$elevel, mrset(hh$age1, hh$age2), hh$HL4, hh$drinkingWater, hh$windex5)
col.vars = list(hh$averagetime, total())
hh.weight = hh$nhhmem
cell.vars = hh$nn

a = calc_cro_rpct(hh,
    cell_vars = cell.vars,
    col_vars = col.vars,
    row_vars = row.vars,
    weight = hh.weight,
    total_row_position = "none") %>% data.frame() %>% select(-1)


b = calc_cro_cases(
    hh,
    cell_vars = cell.vars,
    row_vars = row.vars,
    col_vars = total(),
    weight = nhhmem,
    total_row_position = "none"
  ) %>% data.frame() %>%  select(2)



unweighted <- calc_cro_cases(
    hh,
    cell_vars = nn,
    row_vars = row.vars,
    col_vars = total(),
    total_row_position = "none"
  ) %>% data.frame() %>% select(2) %>% 
  mutate(ind = ifelse(X.Total < 25, 1, 
               ifelse(X.Total %in% 25:49, 2,
                      3)))


a = round(a, digits = 1); b = round(b, digits = 0)

tab = a %>% cbind.data.frame(b) 
tab = tab[, -4]



tab = lapply(tab, function(x) ifelse(is.na(x), 0, x)) %>% data.frame()



colnames(tab) = c(levels(as_factor(hh$averagetime))[c(1:4)], "Total", label(hh$nhhmem))

rownames(tab) = c("Total", levels(as_factor(hh$HH6)), levels(as_factor(hh$HH7)),
                   levels(as_factor(hh$elevel)), levels(as_factor(hh$age1)),
                   levels(as_factor(hh$HL4)), levels(as_factor(hh$drinkingWater)),
                   levels(as_factor(hh$windex5)))





for (i in 1:nrow(tab)) 
  for (j in 1:ncol(tab)) 
  {
    tab[i, j] = ifelse(unweighted$ind[i] == 1, "(*)", 
                       ifelse(unweighted$ind[i] == 2, paste0("(", tab[i,j], ")"),
                              tab[i, j])) # else
  }




tab %>% 
  kable(digits = 1, format.args = list(big.mark = ",", scientific = FALSE)) %>% 
  kable_styling(c("striped"), font_size = 12) %>% 
  pack_rows(label(hh$HH6), 2, 3) %>% 
  pack_rows(label(hh$HH7), 4, 10) %>% 
  pack_rows(label(hh$elevel), 11, 15) %>%
  pack_rows(label(hh$age1), 16, 19) %>% 
  pack_rows(label(hh$HL4), 20, 21) %>% 
  pack_rows(label(hh$drinkingWater), 22, 23) %>% 
  pack_rows(label(hh$windex5), 24, 28) %>% 
  add_header_above(c(" " = 1, "Average time spent collecting water per day" = 4, 
                     " " = 2)) %>% 
  add_header_above(c("Table 1.4: Time spent collecting water" = 7)) 







```





# WS 1.5

```{r}



hl <- read_sav(here("Data/Tunisia_hl.sav")) %>% arrange(HH1, HH2, HL1)

hh <- read_sav(here("Data/Tunisia_hh.sav")) %>% filter(HH46 == 1) %>%
  mutate(nhhmem = HH48 * hhweight)


var_lab(hh$nhhmem) = "Number of household members"

source(here("R/drinkingWater.R"))


hh <- hh %>% mutate(sufficentwater = 0) %>% 
  mutate(sufficentwater = ifelse(WS7 == 2, 100, sufficentwater))

var_lab(hh$sufficentwater) = "Percentage of household population with drinking water available in sufficient quantities [1]"


hh <- hh %>% mutate(nmemnotsufficent = ifelse(!is.na(WS8), 1, 0))


var_lab(hh$nmemnotsufficent) = "Number of household members unable to access water in sufficient quantities when needed"

hh <- hh %>% mutate(WS8 = ifelse(WS8 == 8, 9, WS8)); 
val_lab(hh$WS8) = make_labels("
1 EAU NON DISSPONIBLE A LA SOURCE
3 SOURCE PAS ACCESSIBLE
6 AUTRE

                              9 DK/Missing
                              ")

var_lab(hh$WS8) = "Main reason that the household members are unable to access water in sufficient quantities"





```

## SFR 1.5

```{r}






hh$nn = 1






row.vars = list(total(), hh$HH6, hh$HH7, hh$helevel, hh$drinkingWater, hh$windex5)
col.vars = list(hh$sufficentwater, hh$WS8, hh$nmemnotsufficent, total())
hh.weight = hh$nhhmem
cell.vars = hh$nn



taba = calc_cro_rpct(hh, cell_vars = total(),
               row_vars = row.vars, col_vars = hh$sufficentwater, 
               weight = hh.weight, total_row_position = "none") %>% data.frame() %>% select(3) %>% round(digits = 1)

tabb = calc_cro_cases(hh,
                   cell_vars = cell.vars, row_vars = row.vars, 
                   col_vars = total(), weight = hh.weight, total_row_position = "none") %>% data.frame() %>% select(2) %>% round(digits = 0)

tabc = calc_cro_rpct(hh,
                  cell_vars = cell.vars, 
                  row_vars = row.vars, 
                  col_vars = list(hh$WS8, total()),
                  weight = hh.weight, total_row_position = "none") %>% data.frame() %>% select(-1) %>% round(digits = 1)

tabd = calc_cro_cases(hh, cell_vars = cell.vars, row_vars = row.vars, col_vars = hh$nmemnotsufficent,
                      weight = hh.weight, total_row_position = "none") %>% data.frame() %>% select(3) %>% round(digits = 0)


tab = taba %>% cbind(tabb, tabc, tabd)



unweighted <- calc_cro_cases(
    hh,
    cell_vars = nn,
    row_vars = row.vars,
    col_vars = total(),
    total_row_position = "none"
  ) %>% data.frame() %>% select(2) %>% 
  mutate(ind = ifelse(X.Total < 25, 1, 
               ifelse(X.Total %in% 25:49, 2,
                      3)))



# tab = lapply(tab, function(x) ifelse(is.na(x), 0, x)) %>% data.frame()



colnames(tab) = c(label(hh$sufficentwater), label(hh$nhhmem), levels(as_factor(hh$WS8)), "total", label(hh$nmemnotsufficent))

rownames(tab) = c("Total", levels(as_factor(hh$HH6)), levels(as_factor(hh$HH7)),
                   levels(as_factor(hh$helevel)), levels(as_factor(hh$drinkingWater)),
                   levels(as_factor(hh$windex5)))





for (i in 1:nrow(tab)) 
  for (j in 1:ncol(tab)) 
  {
    tab[i, j] = ifelse(unweighted$ind[i] == 1, "(*)", 
                       ifelse(unweighted$ind[i] == 2, paste0("(", tab[i,j], ")"),
                              tab[i, j])) # else
  }




tab %>% 
  kable(digits = 1, format.args = list(big.mark = ",", scientific = FALSE)) %>% 
  kable_styling(c("striped"), font_size = 12) %>% 
  pack_rows(label(hh$HH6), 2, 3) %>% 
  pack_rows(label(hh$HH7), 4, 10) %>% 
  pack_rows(label(hh$helevel), 11, 15) %>%
  pack_rows(label(hh$drinkingWater), 16, 17) %>% 
  pack_rows(label(hh$windex5), 18, 22) %>% 
  add_header_above(c(" " = 3, "Main reason that the household members are unable to access water in sufficient quantities" = 5, " " = 1)) %>% 
  add_header_above(c("Table WS 1.5: Availability of sufficient drinking water when needed \n Percentage of household members with drinking water
                   available when needed and percent distribution of the main reasons 
                   household members unable to access water in suficient quantities when needed" = 9))
  






```






# WS 1.6

E. Coli

```{r}



hh <- read_sav(here("Data/Tunisia_hh.sav")) %>% arrange(HH1, HH2) %>% 
  filter(WQ31 == 1) %>% 
  mutate(wqsweightHH48 = 0) %>% 
  mutate(wqsweightHH48 = ifelse(wqsweight > 0, wqsweight * HH48, wqsweightHH48)) %>% 
  mutate(nhhmem = wqsweightHH48)

var_lab(hh$nhhmem) = "Number of household members"


hh <- hh %>% mutate(EC_100_S = NA) %>% 
  mutate(EC_100_S = ifelse(WQ27 < 997 & WQ27 >= 100, 101,
                           ifelse(WQ27 < 101 | WQ27 >= 997, WQ27, EC_100_S)))

hh <- hh %>% mutate(Risk_S = ifelse(EC_100_S %in% 1:10, 1,
                                      ifelse(EC_100_S %in% 11:100, 2,
                                             ifelse(EC_100_S == 101, 3,
                                                    ifelse(EC_100_S >= 102, 9, EC_100_S)))))




var_lab(hh$Risk_S) = "Risk level based on number of E. coli per 100 mL"
val_lab(hh$Risk_S) = make_labels("
                                 0 Low (<1 per 100 mL)
                                 1 Moderate (1-10 per 100 mL)
                                 2 High (11-100 per 100 mL)
                                 3 Very high (>100 per 100 mL)
                                 9 DK/Missing
                                 ")


hh <- hh %>% mutate(EC_S = 0) %>% mutate(EC_S = ifelse(!Risk_S == 0, 100, 0))
var_lab(hh$EC_S) = "Percentage of household population with  E. coli in source water [1]"


hh <- hh %>% filter(Risk_S <= 3)


hh <- hh %>%
  mutate(impdrinkingWaterSource = ifelse(WS1 %in% 11:14, 11,
                                                    ifelse(WS1 == 21, 12,
                                                           ifelse(WS1 %in% c(31, 41), 13,
                                                                  ifelse(WS1 == 51, 14,
                                                                         ifelse(WS1 == 72, 15,
                                                                                ifelse(WS1 %in% c(61, 71), 16,
                                                                                       ifelse(WS1 %in% 91:92, 17, WS1)))))))) # else WS1?

hh = hh %>% mutate(unimpdrinkingWaterSource = ifelse(WS1 %in% c(32, 42), 21, 22))




hh <- hh %>% mutate(watersource = ifelse(impdrinkingWaterSource %in% 11:17, 10, 
                                         ifelse(unimpdrinkingWaterSource %in% 21:22, 20, NA)))



var_lab(hh$watersource) = "Main source of drinking water[A]"
val_lab(hh$watersource) = make_labels("
  10 Improved sources
  11 Piped water
  12 Tubewell/Borehole
  13 Protected well or spring
  14 Rainwater collection
  15 Water kiosk	  				 
  16 Tanker-truck/Cart will small tank
  17 Bottled/Sachet water
  20 Unimproved sources
  21 Unprotected well or spring
  22 Surface water/Other
                                      ")










```

(come back around to tables all at once to attempt automation / function wrappers etc)


## SFR 1.6

```{r}



# mrset(hh$watersource, hh$impdrinkingWaterSource, hh$unimpdrinkingWaterSource)

hh$nn = 1


row.vars = list(total(), hh$HH6, hh$HH7, hh$helevel, mrset(hh$watersource, hh$impdrinkingWaterSource, hh$unimpdrinkingWaterSource),
                hh$windex5)

col.vars = list(hh$sufficentwater, hh$WS8, hh$nmemnotsufficent, total())
hh.weight = hh$nhhmem
cell.vars = hh$nn



taba = calc_cro_rpct(hh, cell_vars = cell.vars,
               row_vars = row.vars, 
               col_vars = list(hh$Risk_S, total()), 
               weight = hh.weight, total_row_position = "none") %>% data.frame() %>% select(-1) %>% select(1:4, 6) %>% 
  slice(-c(27:30)) %>% round(digits = 1)



tabb = calc_cro_rpct(hh,
                   cell_vars = cell.vars, row_vars = row.vars, 
                   col_vars = hh$EC_S, weight = hh.weight, total_row_position = "none") %>% 
  data.frame() %>% slice(-c(27:30)) %>% select(3) %>% round(digits = 1)



tabc = calc_cro_cases(hh,
                  cell_vars = cell.vars, 
                  row_vars = row.vars, 
                  col_vars = total(),
                  weight = hh.weight, total_row_position = "none") %>% data.frame() %>% 
  select(2) %>% round(digits = 1) %>% slice(-c(27:30))


tab = taba %>% cbind(tabb, tabc)



unweighted <- calc_cro_cases(
    hh,
    cell_vars = nn,
    row_vars = row.vars,
    col_vars = total(),
    total_row_position = "none"
  ) %>% data.frame() %>% select(2) %>% 
  mutate(ind = ifelse(X.Total < 25, 1, 
               ifelse(X.Total %in% 25:49, 2,
                      3))) %>% slice(-c(27:30))





colnames(tab) = c(levels(as_factor(hh$Risk_S))[1:4], "Total", label(hh$EC_S), label(hh$nhhmem))

rownames(tab) = c("Total", levels(as_factor(hh$HH6)), levels(as_factor(hh$HH7)),
                   levels(as_factor(hh$helevel)), levels(as_factor(hh$watersource)),
                   levels(as_factor(hh$windex5)))





for (i in 1:nrow(tab)) 
  for (j in 1:ncol(tab)) 
  {
    tab[i, j] = ifelse(unweighted$ind[i] == 1, "(*)", 
                       ifelse(unweighted$ind[i] == 2, paste0("(", tab[i,j], ")"),
                              tab[i, j])) # else
  }




tab %>% 
  kable(digits = 1, format.args = list(big.mark = ",", scientific = FALSE)) %>% 
  kable_styling(c("striped"), font_size = 12) %>% 
  pack_rows(label(hh$HH6), 2, 3) %>% 
  pack_rows(label(hh$HH7), 4, 10) %>% 
  pack_rows(label(hh$helevel), 11, 15) %>%
  pack_rows(label(hh$watersource), 16, 25) %>% 
  pack_rows(label(hh$windex5), 26, 30) %>% 
  add_header_above(c(" " = 2, "Risk level based on the number of E. coli per 100 mL" = 4, " " = 2)) %>% 
  add_header_above(c("Table WS 1.6: Quality of source drinking water \n Percentage of household population at risk of faecal contamination based on
                     number of E. coli detected in source drinking water," = 8))
  









```










# WS 1.7


```{r}

hh <- read_sav(here("Data/Tunisia_hh.sav")) 

hh = hh %>% mutate(HHAGEx = ifelse(HHAGE %in% 15:19, 1,
                                   ifelse(HHAGE %in% 20:24, 2,
                                          ifelse(HHAGE %in% 25:49, 3,
                                                 ifelse(HHAGE >= 50, 4, HHAGE)))))

var_lab(hh$HHAGEx) = "Age of household head"

hh = hh %>% mutate(HHAGEy = ifelse(HHAGE %in% 15:19, 1,
                                   ifelse(HHAGE %in% 20:24, 2,
                                          ifelse(HHAGE %in% 25:29, 3,
                                                 ifelse(HHAGE %in% 30:34, 4,
                                                        ifelse(HHAGE %in% 35:39, 5, 
                                                               ifelse(HHAGE %in% 40:44, 6,
                                                                      ifelse(HHAGE %in% 45:49, 7,
                                                                             ifelse(HHAGE %in% 50:59, 8,
                                                                                    ifelse(HHAGE %in% 60:69, 9,
                                                                                           ifelse(HHAGE >= 70, 10, HHAGE)))))))))))


var_lab(hh$HHAGEy) = "Age of household head"


hh = hh %>% arrange(HH1, HH2) %>% 
  filter(WQ31 == 1) %>% 
  mutate(wqhweightHH48 = 0) %>% 
  mutate(wqhweightHH48 = ifelse(wqhweight > 0, wqhweight * HH48, wqhweightHH48)) %>% 
  mutate(nhhmem = wqhweightHH48)







hh <- hh %>% mutate(EC_100_H = NA) %>%
  mutate(EC_100_H = ifelse(WQ26 < 998 & WQ26 >= 100, 101,
                           ifelse(WQ26 < 101 | WQ26 >= 997, WQ26, EC_100_H)))




hh <- hh %>% mutate(Risk_H = ifelse(EC_100_H %in% 1:10, 1,
                                    ifelse(EC_100_H %in% 11:100, 2,
                                           ifelse(EC_100_H == 101, 3,
                                                  ifelse(EC_100_H >= 102, 9, EC_100_H)))))


var_lab(hh$EC_100_H) = "Risk level based on number of E. coli per 100 mL"
val_lab(hh$EC_100_H) = make_labels("
                                   0 Low (<1 per 100 mL) 
                                   1 Moderate (1-10 per 100 mL) 
                                   2 High (11-100 per 100 mL) 
                                   3 Very high (>100 per 100 mL) 
                                   9 DK/Missing
                                   ")



hh = hh %>% mutate(EC_H = 0) %>% 
  mutate(EC_H = ifelse(!Risk_H == 0, 100, EC_H))

var_lab(hh$EC_H) = "Percentage of household population with  E. coli in household drinking water [1]"


hh = hh %>% filter(Risk_H <= 3)






hh <- hh %>%
  mutate(impdrinkingWaterSource = ifelse(WS1 %in% 11:14, 11,
                                                    ifelse(WS1 == 21, 12,
                                                           ifelse(WS1 %in% c(31, 41), 13,
                                                                  ifelse(WS1 == 51, 14,
                                                                         ifelse(WS1 == 72, 15,
                                                                                ifelse(WS1 %in% c(61, 71), 16,
                                                                                       ifelse(WS1 %in% 91:92, 17, WS1)))))))) # else WS1?

hh = hh %>% mutate(unimpdrinkingWaterSource = ifelse(WS1 %in% c(32, 42), 21, 22))




hh <- hh %>% mutate(watersource = ifelse(impdrinkingWaterSource %in% 11:17, 10, 
                                         ifelse(unimpdrinkingWaterSource %in% 21:22, 20, NA)))



val_lab(hh$watersource) = make_labels("
  10 Improved sources
  11 Piped water
  12 Tubewell/Borehole
  13 Protected well or spring
  14 Rainwater collection
  15 Water kiosk	  				 
  16 Tanker-truck/Cart will small tank
  17 Bottled/Sachet water
  20 Unimproved sources
  21 Unprotected well or spring
  22 Surface water/Other
                                      ")


var_lab(hh$Risk_H) = "Risk level based on number of E. coli per 100 mL"
val_lab(hh$Risk_H) = make_labels("
                                 0 Low (<1 per 100 mL)
                                 1 Moderate (1-10 per 100 mL)
                                 2 High (11-100 per 100 mL)
                                 3 Very high (>100 per 100 mL)
                                 9 DK/Missing
                                 ")

var_lab(hh$nhhmem) = "Number of household members"


```



## SFR 1.7


```{r}


# mrset(hh$watersource, hh$impdrinkingWaterSource, hh$unimpdrinkingWaterSource)

hh$nn = 1


row.vars = list(total(), hh$HH6, hh$HH7, hh$helevel, mrset(hh$watersource, hh$impdrinkingWaterSource, hh$unimpdrinkingWaterSource),
                hh$windex5)

col.vars = list(hh$sufficentwater, hh$WS8, hh$nmemnotsufficent, total())
hh.weight = hh$nhhmem
cell.vars = hh$nn



taba = calc_cro_rpct(hh, cell_vars = cell.vars,
               row_vars = row.vars, 
               col_vars = list(hh$Risk_H, total()), 
               weight = hh.weight, total_row_position = "none") %>% data.frame() %>% select(c(2:5, 7)) %>% 
  slice(-c(27:30)) %>% round(digits = 1)



tabb = calc_cro_rpct(hh,
                   cell_vars = cell.vars, row_vars = row.vars, 
                   col_vars = hh$EC_H, weight = hh.weight, total_row_position = "none") %>% 
  data.frame() %>% slice(-c(27:30)) %>% select(3) %>% round(digits = 1)



tabc = calc_cro_cases(hh,
                  cell_vars = cell.vars, 
                  row_vars = row.vars, 
                  col_vars = total(),
                  weight = hh.weight, total_row_position = "none") %>% data.frame() %>% 
  select(2) %>% round(digits = 0) %>% slice(-c(27:30))


tab = taba %>% cbind(tabb, tabc)



unweighted <- calc_cro_cases(
    hh,
    cell_vars = nn,
    row_vars = row.vars,
    col_vars = total(),
    total_row_position = "none"
  ) %>% data.frame() %>% select(2) %>% 
  mutate(ind = ifelse(X.Total < 25, 1, 
               ifelse(X.Total %in% 25:49, 2,
                      3))) %>% slice(-c(27:30))





colnames(tab) = c(levels(as_factor(hh$Risk_H))[1:4], "Total", label(hh$EC_H), label(hh$nhhmem))

rownames(tab) = c("Total", levels(as_factor(hh$HH6)), levels(as_factor(hh$HH7)),
                   levels(as_factor(hh$helevel)), levels(as_factor(hh$watersource)),
                   levels(as_factor(hh$windex5)))





for (i in 1:nrow(tab)) 
  for (j in 1:ncol(tab)) 
  {
    tab[i, j] = ifelse(unweighted$ind[i] == 1, "(*)", 
                       ifelse(unweighted$ind[i] == 2, paste0("(", tab[i,j], ")"),
                              tab[i, j])) # else
  }




tab %>% 
  kable(digits = 1, format.args = list(big.mark = ",", scientific = FALSE)) %>% 
  kable_styling(c("striped"), font_size = 12) %>% 
  pack_rows(label(hh$HH6), 2, 3) %>% 
  pack_rows(label(hh$HH7), 4, 10) %>% 
  pack_rows(label(hh$helevel), 11, 15) %>%
  pack_rows(label(hh$watersource), 16, 25) %>% 
  pack_rows(label(hh$windex5), 26, 30) %>% 
  add_header_above(c(" " = 2, "Risk level based on the number of E. coli per 100 mL" = 4, " " = 2)) %>% 
  add_header_above(c("Table WS 1.7: Quality of source drinking water \n Percentage of household population at risk of faecal contamination based on
                     number of E. coli detected in source drinking water," = 8))
  





```





# WS 1.8

```{r}




hh <- read_sav(here("Data/Tunisia_hh.sav")) %>% arrange(HH1, HH2) %>% 
  filter(WQ31 == 1) %>% 
  mutate(wqsweightHH48 = 0) %>% 
  mutate(wqsweightHH48 = ifelse(wqsweight > 0, wqsweight * HH48, wqsweightHH48)) %>% 
  mutate(nhhmem = wqsweightHH48)

var_lab(hh$nhhmem) = "Number of household members"

source(here("R/drinkingWater.R"))


hh <- hh %>% mutate(EC_100_S = NA) %>% 
  mutate(EC_100_S = ifelse(WQ27 < 997 & WQ27 >= 100, 101,
                           ifelse(WQ27 < 101 | WQ27 >= 997, WQ27, EC_100_S)))


hh <- hh %>% mutate(Risk_S = ifelse(EC_100_S %in% 1:10, 1,
                                      ifelse(EC_100_S %in% 11:100, 2,
                                             ifelse(EC_100_S == 101, 3,
                                                    ifelse(EC_100_S >= 102, 9, EC_100_S)))))


var_lab(hh$Risk_S) = "Risk level based on number of E. coli per 100 mL"
val_lab(hh$Risk_S) = make_labels("
                                 0 Low (<1 per 100 mL)
                                 1 Moderate (1-10 per 100 mL)
                                 2 High (11-100 per 100 mL)
                                 3 Very high (>100 per 100 mL)
                                 9 DK/Missing
                                 ")




hh = hh %>% mutate(WithoutEC_S = 0) %>% 
  mutate(WithoutEC_S = ifelse(Risk_S == 0, 100, WithoutEC_S))


var_lab(hh$WithoutEC_S) = "Without E. coli in drinking water source"


hh <- hh %>% mutate(sufficentwater = 0) %>% 
  mutate(sufficentwater = ifelse(WS7 == 2, 100, sufficentwater))

var_lab(hh$sufficentwater) = "Percentage of household population with drinking water available in sufficient quantities [1]"



hh = hh %>% mutate(wpremises = 0) %>% 
  mutate(wpremises = ifelse(WS1 %in% 11:13 | WS2 %in% 11:13 | WS3 %in% 1:2, 100, wpremises))

var_lab(hh$wpremises) = "Drinking water accessible on premises"



hh = hh %>% mutate(indSDG611 = 0) %>% 
  mutate(indSDG611 = ifelse(drinkingWater == 1 & WithoutEC_S == 100 & sufficentwater == 100 & wpremises == 100, 100, indSDG611))



hh = hh %>% filter(Risk_S <= 3)



hh <- hh %>%
  mutate(impdrinkingWaterSource = ifelse(WS1 %in% 11:14, 11,
                                                    ifelse(WS1 == 21, 12,
                                                           ifelse(WS1 %in% c(31, 41), 13,
                                                                  ifelse(WS1 == 51, 14,
                                                                         ifelse(WS1 == 72, 15,
                                                                                ifelse(WS1 %in% c(61, 71), 16,
                                                                                       ifelse(WS1 %in% 91:92, 17, WS1)))))))) # else WS1?

hh = hh %>% mutate(unimpdrinkingWaterSource = ifelse(WS1 %in% c(32, 42), 21, 22))




hh <- hh %>% mutate(watersource = ifelse(impdrinkingWaterSource %in% 11:17, 10, 
                                         ifelse(unimpdrinkingWaterSource %in% 21:22, 20, NA)))


val_lab(hh$watersource) = make_labels("
  10 Improved sources
  11 Piped water
  12 Tubewell/Borehole
  13 Protected well or spring
  14 Rainwater collection
  15 Water kiosk	  				 
  16 Tanker-truck/Cart will small tank
  17 Bottled/Sachet water
  20 Unimproved sources
  21 Unprotected well or spring
  22 Surface water/Other
                                      ")






```




## SFR 1.8


```{r, eval = F}




# mrset(hh$watersource, hh$impdrinkingWaterSource, hh$unimpdrinkingWaterSource)

hh$nn = 1


row.vars = list(total(), hh$HH6, hh$HH7, hh$helevel, mrset(hh$watersource, hh$impdrinkingWaterSource, hh$unimpdrinkingWaterSource),
                hh$windex5)

col.vars = list(hh$sufficentwater, hh$WS8, hh$nmemnotsufficent, total())
hh.weight = hh$nhhmem
cell.vars = hh$nn



taba = calc_cro_rpct(hh, cell_vars = total(),
               row_vars = row.vars, 
               col_vars = list(hh$WithoutEC_S, hh$sufficentwater, hh$wpremises, hh$indSDG611), 
               weight = hh.weight, total_row_position = "none") %>% data.frame() %>% slice(-c(27:30)) %>% 
  select(c(3, 5, 7, 9, 10:12)) %>% 
    round(digits = 1)



tabb = calc_cro_rpct(hh,
                   cell_vars = cell.vars, row_vars = row.vars, 
                   col_vars = hh$EC_H, weight = hh.weight, total_row_position = "none") %>% 
  data.frame() %>% slice(-c(27:30)) %>% select(3) %>% round(digits = 1)



tabc = calc_cro_cases(hh,
                  cell_vars = cell.vars, 
                  row_vars = row.vars, 
                  col_vars = total(),
                  weight = hh.weight, total_row_position = "none") %>% data.frame() %>% 
  select(2) %>% round(digits = 0) %>% slice(-c(27:30))


tab = taba %>% cbind(tabb, tabc)



unweighted <- calc_cro_cases(
    hh,
    cell_vars = nn,
    row_vars = row.vars,
    col_vars = total(),
    total_row_position = "none"
  ) %>% data.frame() %>% select(2) %>% 
  mutate(ind = ifelse(X.Total < 25, 1, 
               ifelse(X.Total %in% 25:49, 2,
                      3))) %>% slice(-c(27:30))





colnames(tab) = c(levels(as_factor(hh$Risk_H))[1:4], "Total", label(hh$EC_H), label(hh$nhhmem))

rownames(tab) = c("Total", levels(as_factor(hh$HH6)), levels(as_factor(hh$HH7)),
                   levels(as_factor(hh$helevel)), levels(as_factor(hh$watersource)),
                   levels(as_factor(hh$windex5)))





for (i in 1:nrow(tab)) 
  for (j in 1:ncol(tab)) 
  {
    tab[i, j] = ifelse(unweighted$ind[i] == 1, "(*)", 
                       ifelse(unweighted$ind[i] == 2, paste0("(", tab[i,j], ")"),
                              tab[i, j])) # else
  }




tab %>% 
  kable(digits = 1, format.args = list(big.mark = ",", scientific = FALSE)) %>% 
  kable_styling(c("striped"), font_size = 12) %>% 
  pack_rows(label(hh$HH6), 2, 3) %>% 
  pack_rows(label(hh$HH7), 4, 10) %>% 
  pack_rows(label(hh$helevel), 11, 15) %>%
  pack_rows(label(hh$watersource), 16, 25) %>% 
  pack_rows(label(hh$windex5), 26, 30) %>% 
  add_header_above(c(" " = 2, "Risk level based on the number of E. coli per 100 mL" = 4, " " = 2)) %>% 
  add_header_above(c("Table WS 1.7: Quality of source drinking water \n Percentage of household population at risk of faecal contamination based on
                     number of E. coli detected in source drinking water," = 8))
  







```







# WS 1.9

```{r}

hh <- read_sav(here("Data/Tunisia_hh.sav"))

hh <- hh %>% filter(HH46 == 1) %>% 
  mutate(hhweightHH48 = HH48 * hhweight) %>% mutate(nhhmem = 1 * hhweightHH48)

var_lab(hh$nhhmem) = "Number of household members"; 
val_lab(hh$nhhmem) = make_labels("
1                        ")



hh <- hh %>% mutate(treat = 1)
val_lab(hh$treat) = make_labels("
                                1 Water treatment method used in the household
                                ")


hh <- hh %>% mutate(none = 0) %>% 
  mutate(none = ifelse(!WS9 == 1, 100, none))




hh <- hh %>% mutate(boil = ifelse(WS10A == "A", 100, 0)); var_lab(hh$boil) = "Boil"

hh <- hh %>% mutate(bleach = ifelse(WS10B == "B", 100, 0),
                    cloth = ifelse(WS10C == "C", 100, 0),
                    waterFilter = ifelse(WS10D == "D", 100, 0),
                    solar = ifelse(WS10E == "E", 100, 0),
                    stand = ifelse(WS10F == "F", 100, 0),
                    other = ifelse(WS10X == "X", 100, 0),
                    dkmissing = ifelse(WS10Z == "Z" | WS10NR == "?", 100, 0))



source(here("R/drinkingWater.R"))



hh <- hh %>% mutate(appropriate = 0) %>% 
  mutate(appropriate = ifelse(boil == 100 | bleach == 100 | waterFilter == 100 | solar == 100, 100, appropriate))


var_lab(hh$appropriate) = "Percentage of household members in households using an appropriate water treatment method"




var.labs = list(boil = "Boil", bleach = "Add bleach / chlorine", cloth = "Strain through a cloth",
                waterFilter = "Use water filter", solar = "Solar disinfection", stand = "Let it stand and settle", other = "Other", dkmissing = "Dk/Missing")


var_lab(hh$boil) = "Boil"; var_lab(hh$bleach) = "Add bleach / chlorine"; var_lab(hh$cloth) = "Strain through a cloth"
var_lab(hh$waterFilter) = "Use water filter"; var_lab(hh$solar) = "Solar disinfection"; var_lab(hh$stand) = "Let it stand and settle"
var_lab(hh$other) = "Other"; var_lab(hh$dkmissing) = "DK/Missing"; var_lab(hh$none) = "None"

```



## SFR 1.9

```{r}


# mrset(hh$watersource, hh$impdrinkingWaterSource, hh$unimpdrinkingWaterSource)

hh$nn = 1


row.vars = list(total(), hh$HH6, hh$HH7, hh$helevel, hh$drinkingWater, hh$windex5)

col.vars = list(hh$sufficentwater, hh$WS8, hh$nmemnotsufficent, total())
hh.weight = hh$nhhmem
cell.vars = hh$nn



taba = calc_cro_rpct(hh, hh$nn,
               row_vars = row.vars, 
               col_vars = list(hh$none, hh$boil, hh$bleach, hh$cloth, hh$waterFilter, hh$solar, hh$stand, hh$other, hh$dkmissing, hh$appropriate), 
               weight = hh.weight, total_row_position = "none") %>% data.frame() %>% 
  select(c(3, 5, 7, 9, 11, 13, 15, 17, 18, 20)) %>% round(digits = 1)


tabb = calc_cro_cases(hh, cell_vars = hh$nn,
                      row_vars = row.vars,
                      col_vars = total(),
                      weight = hh.weight, 
                      total_row_position = "none") %>% data.frame() %>% select(2) %>% round(digits = 0)




tab = taba %>% cbind(tabb)
tab[,9] = tab[,9] - 100


unweighted <- calc_cro_cases(
    hh,
    cell_vars = nn,
    row_vars = row.vars,
    col_vars = total(),
    total_row_position = "none"
  ) %>% data.frame() %>% select(2) %>% 
  mutate(ind = ifelse(X.Total < 25, 1, 
               ifelse(X.Total %in% 25:49, 2,
                      3))) 





colnames(tab) = c(label(hh$none), label(hh$boil), label(hh$bleach), label(hh$cloth), label(hh$waterFilter), label(hh$solar),
                  label(hh$stand), label(hh$other), label(hh$dkmissing), label(hh$appropriate), label(hh$nhhmem))

rownames(tab) = c("Total", levels(as_factor(hh$HH6)), levels(as_factor(hh$HH7)),
                   levels(as_factor(hh$helevel)), levels(as_factor(hh$drinkingWater)),
                   levels(as_factor(hh$windex5)))





for (i in 1:nrow(tab)) 
  for (j in 1:ncol(tab)) 
  {
    tab[i, j] = ifelse(unweighted$ind[i] == 1, "(*)", 
                       ifelse(unweighted$ind[i] == 2, paste0("(", tab[i,j], ")"),
                              tab[i, j])) # else
  }




tab %>% 
  kable(digits = 1, format.args = list(big.mark = ",", scientific = FALSE)) %>% 
  kable_styling(c("striped"), font_size = 12) %>% 
  pack_rows(label(hh$HH6), 2, 3) %>% 
  pack_rows(label(hh$HH7), 4, 10) %>% 
  pack_rows(label(hh$helevel), 11, 15) %>%
  pack_rows(label(hh$drinkingWater), 16, 17) %>% 
  pack_rows(label(hh$windex5), 18, 22) %>% 
  add_header_above(c(" " = 2, "Water treatment method used in the household" = 9, " " = 1)) %>% 
  add_header_above(c("Table WS 1.9: Household water treatment \n Percentage of household population by drinking water treatment method used in the
                     household and the percentage who are using an appropriate treatment method" = 12))
  




```



# WS 2.1

```{r}

hh <- read_sav(here("Data/Tunisia_hh.sav"))
hh <- hh %>% filter(HH46 == 1) %>% 
  mutate(hhweightHH48 = HH48 * hhweight) %>% mutate(nhhmem = 1 * hhweightHH48)

var_lab(hh$nhhmem) = "Number of household members"; 
val_lab(hh$nhhmem) = make_labels("
1                        ")


hh <- hh %>% mutate(layer1 = 0,
                    layer2 = 0,
                    fixedobserved = ifelse(HW1 == 1 | HW1 == 2, 100, 0),
                    mobileobserved = ifelse(HW1 == 3, 100, 0),
                    noplace = ifelse(HW1 == 4, 100, 0),
                    nopermission = ifelse(HW1 >= 5, 100, 0))


val_lab(hh$layer1) = make_labels("
                                 0 Handwashing facility observed
                                 ")

val_lab(hh$layer2) = make_labels("
                                 0 Handwashing facility observed and
                                 ")



hh <- hh %>% mutate(numHouseholdsObs = ifelse(fixedobserved == 100 | mobileobserved == 100, 1, 0)) %>% 
  mutate(water = ifelse(HW2 == 1, 100, 0),
         Soap = ifelse(HW7A == "A" | HW7B == "B", 100, 0),
         Ash = ifelse(HW7C == "C", 100, 0),
         numHHObsnoplace = ifelse(fixedobserved == 100 | noplace == 100, 1, 0)) %>% 
  mutate(indWS7 = ifelse(HW2 == 1 & (HW7A == "A" | HW7B == "B"), 100, 0))



var_lab(hh$water) = "water available"; var_lab(hh$Soap) = "soap available"
var_lab(hh$Ash) = "with ash/mud/sand available"

var_lab(hh$indWS7) = "Percentage of household members with handwashing facility where water and soap are present[1]"

val_lab(hh$numHouseholdsObs) = make_labels("
                                           1 Number of household members where handwashing facility was observed
                                           ")

var_lab(hh$fixedobserved) = "Handwashing facility observed"; var_lab(hh$mobileobserved) = "Mobile object observed"
var_lab(hh$noplace) = "No handwashing facility observed in the dwelling, yard, or plot"
var_lab(hh$nopermission) = "No permission to see/Other"
var_lab(hh$numHouseholdsObs) = "Number of household members where handwashing facility was observed"
var_lab(hh$numHHObsnoplace) = "Number of household members where handwashing facility was observed or with no handwashing facility in the dwelling, yard, or plot"


```


## SFR 2.1

```{r}

hh$nn = 1


row.vars = list(total(), hh$HH6, hh$HH7, hh$helevel, hh$windex5)

col.vars = list(hh$sufficentwater, hh$WS8, hh$nmemnotsufficent, total())

hh.weight = hh$nhhmem
cell.vars = hh$nn



taba = calc_cro_rpct(hh, hh$nn,
               row_vars = row.vars, 
               col_vars = list(hh$fixedobserved, hh$mobileobserved, hh$noplace, hh$nopermission, total()), 
               weight = hh.weight, total_row_position = "none") %>% data.frame() %>% select(contains(c("100", "Total"))) %>% 
  round(digits = 1)

tabb = calc_cro_cases(hh, hh$nn, row_vars = row.vars,
                      col_vars = total(), weight = hh.weight, total_row_position = "none") %>% 
  data.frame() %>% select(contains("Total")) %>% round(digits = 0)



tabc = calc_cro_rpct(hh, cell_vars = hh$nn,
                      row_vars = row.vars,
                      col_vars = list(hh$water, hh$Soap, hh$Ash),
                      weight = hh.weight, 
                      total_row_position = "none") %>% data.frame() %>% select(contains("100")) %>% round(digits = 1)


tabd = calc_cro_cases(hh, cell_vars = hh$nn, row_vars = row.vars,
                      col_vars = hh$numHouseholdsObs, weight = hh.weight,
                      total_row_position = "none") %>% data.frame() %>% 
  select(3) %>% round(digits = 0)


tabe = calc_cro_rpct(hh, cell_vars = hh$nn,
                      row_vars = row.vars,
                      col_vars = hh$indWS7,
                      weight = hh.weight, 
                      total_row_position = "none") %>% data.frame() %>% select(contains("100")) %>% round(digits = 1)



tabf = calc_cro_cases(hh, cell_vars = hh$nn, row_vars = row.vars,
                      col_vars = hh$numHHObsnoplace, weight = hh.weight,
                      total_row_position = "none") %>% data.frame() %>% 
  select(contains("1")) %>% round(digits = 0)



tab = cbind(taba, tabb, tabc, tabd, tabe, tabf)


unweighted <- calc_cro_cases(
    hh,
    cell_vars = nn,
    row_vars = row.vars,
    col_vars = total(),
    total_row_position = "none"
  ) %>% data.frame() %>% select(2) %>% 
  mutate(ind = ifelse(X.Total < 25, 1, 
               ifelse(X.Total %in% 25:49, 2,
                      3))) 





colnames(tab) = c(label(hh$fixedobserved), label(hh$mobileobserved), label(hh$noplace), label(hh$nopermission), "Total", label(hh$nhhmem),
                  label(hh$water), label(hh$Soap), label(hh$Ash), label(hh$numHouseholdsObs), label(hh$indWS7), label(hh$numHHObsnoplace))

rownames(tab) = c("Total", levels(as_factor(hh$HH6)), levels(as_factor(hh$HH7)),
                   levels(as_factor(hh$helevel)),
                   levels(as_factor(hh$windex5)))





for (i in 1:nrow(tab)) 
  for (j in 1:ncol(tab)) 
  {
    tab[i, j] = ifelse(unweighted$ind[i] == 1, "(*)", 
                       ifelse(unweighted$ind[i] == 2, paste0("(", tab[i,j], ")"),
                              tab[i, j])) # else
  }




tab %>% 
  kable(digits = 1, format.args = list(big.mark = ",", scientific = FALSE)) %>% 
  kable_styling(c("striped"), font_size = 12) %>% 
  pack_rows(label(hh$HH6), 2, 3) %>% 
  pack_rows(label(hh$HH7), 4, 10) %>% 
  pack_rows(label(hh$helevel), 11, 15) %>%
  pack_rows(label(hh$windex5), 16, 20) %>% 
  add_header_above(c(" " = 1, "Handwashing facility observed" = 2, " " = 4, "Handwashing facility observed and" = 3, " " = 3)) %>% 
  add_header_above(c("Table WS 2.1: Handwashing facility with soap and water on premises \n
                     Percent distribution of household members by observation of handwashing facility and percentage of household members by availability of water and soap or detergent at the handwashing facility" = 13))
  



```








# WS 3.1

```{r}


hh <- read_sav(here("Data/Tunisia_hh.sav"))
hh <- hh %>% filter(HH46 == 1) %>% 
  mutate(hhweightHH48 = HH48 * hhweight) %>% mutate(nhhmem = 1 * hhweightHH48)

var_lab(hh$nhhmem) = "Number of household members"; 
val_lab(hh$nhhmem) = make_labels("
1                        ")



source(here("R/drinkingWater.R"))


hh <- hh %>% mutate(WS11 = ifelse(WS11 %in% 97:99, 99, WS11))
val_lab(hh$WS11) = make_labels("
  95  
	99 DK/Missing
                               ")




hh <- hh %>% mutate(improvepercent = ifelse(toiletType == 1, 100, 0)); var_lab(hh$improvepercent) = "Percentage using improved sanitation [1]"

hh = hh %>% mutate(WS14 = ifelse(WS11 == 95, 4, WS14)); var_lab(hh$WS14) = "Location of sanitation facility"
val_lab(hh$WS14) = make_labels("
                               4 Open defecation (no facility, bush, field)
                               ")



var_lab(hh$toiletType) = "Type of sanitation facility used by household"
val_lab(hh$toiletType) = make_labels("
                                     1 Improved sanitation facility
                                     2 Unimproved sanitation facility
                                     3 Open defecation (no facility, bush, field)
                                     ")






```


## SFR 3.1

```{r}




```





#WS 3.2

```{r}
hh <- read_sav(here("Data/Tunisia_hh.sav"))

hh <- hh %>% filter(HH46 == 1) %>% 
  mutate(hhweightHH48 = HH48 * hhweight) %>% mutate(nhhmem = 1 * hhweightHH48)

var_lab(hh$nhhmem) = "Number of household members"; 
val_lab(hh$nhhmem) = make_labels("
1                        ")



source(here("R/drinkingWater.R"))



hh = hh %>% mutate(shared1 = ifelse(toiletType == 1, sharedToilet, NA))

var_lab(hh$shared1) = "Users of improved sanitation facilities"
val_lab(hh$shared1) = make_labels("
  0 Not shared [1]
  1 Shared by: 5 households or less
  2 Shared by: More than 5 households
  3 Public facility
  9 DK/Missing
                                  ")


hh = hh %>% mutate(shared2 = ifelse(toiletType == 2, sharedToilet, NA))
var_lab(hh$shared2) = "Users of unimproved sanitation facilities"
val_lab(hh$shared2) = make_labels("
  0 Not shared
  1 Shared by: 5 households or less
  2 Shared by: More than 5 households
  3 Public facility
  9 DK/Missing
                                  ")




hh = hh %>% mutate(shared3 = ifelse(toiletType == 3, 1, NA))

hh = hh %>% mutate(WS14 = ifelse(WS11 == 95, 4, WS14))
var_lab(hh$WS14) = "Location of sanitation facility"






```




#WS 3.3

```{r}

hh <- read_sav(here("Data/Tunisia_hh.sav")) %>% 
  mutate(onsite = ifelse(WS11 == 12, 1,
                         ifelse(WS11 %in% c(13, 21, 22, 31), 2, 0)))

var_lab(hh$onsite) = "Type of onsite sanitation facility"

hh = hh %>% filter(HH46 == 1, !onsite == 0) %>% 
  mutate(hhweightHH48 = HH48 * hhweight) %>% mutate(nhhmem = 1 * hhweightHH48)

var_lab(hh$nhhmem) = "Number of household members"; 
val_lab(hh$nhhmem) = make_labels("
1                        ")


source(here("R/drinkingWater.R"))

# septic tank

hh <- hh %>% mutate(septicemptiedproviderplant = ifelse(onsite == 1 & WS13 == 1, 100, 0),
                    septicemptiedproviderDK = ifelse(onsite == 1 & WS13 == 3, 100, 0),
                    septicemptiedpit = ifelse(onsite == 1 & (WS13 == 2 | WS13 == 4), 100, 0),
                    septicemptiedHHpit = ifelse(onsite == 1 & WS13 == 5, 100, 0),
                    septicemptiedother = ifelse(onsite == 1 & WS13 == 6, 100, 0),
                    septicemptiedDK = ifelse(onsite == 1 & WS13 == 8, 100, 0),
                    septicneveremptied = ifelse(onsite == 1 & WS12 == 4, 100, 0),
                    septicDKemptied = ifelse(onsite == 1 & WS12 >= 8, 100, 0))

# other improved on-site sanitation facilities
hh <- hh %>% mutate(Oonsiteemptiedproviderplant = ifelse(onsite == 2 & WS13 == 1, 100, 0),
                    OonsiteemptiedproviderDK = ifelse(onsite == 2 & WS13 == 3, 100, 0),
                    Oonsiteemptiedpit = ifelse(onsite == 2 & (WS13 == 2 | WS13 == 4), 100, 0),
                    OonsiteemptiedHHpit = ifelse(onsite == 2 & WS13 == 5, 100, 0),
                    Oonsiteemptiedother = ifelse(onsite == 2 & WS13 == 6, 100, 0),
                    OonsiteemptiedDK = ifelse(onsite == 1 & WS13 == 8, 100, 0),
                    Oonsiteneveremptied = ifelse(onsite == 2 & WS12 == 4, 100, 0),
                    OonsiteDKemptied = ifelse(onsite == 2 & WS12 >= 8, 100, 0))


hh = hh %>% mutate(safedisposal = ifelse(septicemptiedpit == 100 | septicneveremptied == 100 | septicDKemptied == 100 | Oonsiteemptiedpit == 100 |
                                           Oonsiteneveremptied == 100 | OonsiteDKemptied == 100, 100, 0),
                   unsafedisposal = ifelse(septicemptiedHHpit == 100 | septicemptiedother == 100 | OonsiteemptiedHHpit == 100 |
                                             Oonsiteemptiedother == 100, 100, 0),
                   treatment = ifelse(septicemptiedproviderplant == 100 | septicemptiedproviderDK == 100 | septicemptiedDK == 100 | 
                                        Oonsiteemptiedproviderplant == 100 | OonsiteemptiedproviderDK == 100 | OonsiteemptiedDK == 100, 100, 0))


hh = hh %>% mutate(layer1 = 0, layer2 = 0)
hh = hh %>% mutate(WS11c = ifelse(is.na(WS11), 12, WS11))








```


#WS 3.4

```{r}


hh <- read_sav(here("Data/Tunisia_hh.sav"))


source(here("R/commonVarsHH.R"))

hh = hh %>% filter(HH46 == 1) %>% 
  mutate(onsite = ifelse(WS11 == 12, 1,
                         ifelse(WS11 %in% c(13, 21, 22, 31), 2, 0)))


source(here("R/drinkingWater.R"))



hh = hh %>% filter(HH46 == 1) %>% 
  mutate(hhweightHH48 = HH48 * hhweight) %>% mutate(nhhmem = 1 * hhweightHH48)

var_lab(hh$nhhmem) = "Number of household members"; 
val_lab(hh$nhhmem) = make_labels("
1                        ")



# septic tank

hh <- hh %>% mutate(septicemptiedproviderplant = ifelse(onsite == 1 & WS13 == 1, 100, 0),
                    septicemptiedproviderDK = ifelse(onsite == 1 & WS13 == 3, 100, 0),
                    septicemptiedpit = ifelse(onsite == 1 & (WS13 == 2 | WS13 == 4), 100, 0),
                    septicemptiedHHpit = ifelse(onsite == 1 & WS13 == 5, 100, 0),
                    septicemptiedother = ifelse(onsite == 1 & WS13 == 6, 100, 0),
                    septicemptiedDK = ifelse(onsite == 1 & WS13 == 8, 100, 0),
                    septicneveremptied = ifelse(onsite == 1 & WS12 == 4, 100, 0),
                    septicDKemptied = ifelse(onsite == 1 & WS12 >= 8, 100, 0))

# other improved on-site sanitation facilities
hh <- hh %>% mutate(Oonsiteemptiedproviderplant = ifelse(onsite == 2 & WS13 == 1, 100, 0),
                    OonsiteemptiedproviderDK = ifelse(onsite == 2 & WS13 == 3, 100, 0),
                    Oonsiteemptiedpit = ifelse(onsite == 2 & (WS13 == 2 | WS13 == 4), 100, 0),
                    OonsiteemptiedHHpit = ifelse(onsite == 2 & WS13 == 5, 100, 0),
                    Oonsiteemptiedother = ifelse(onsite == 2 & WS13 == 6, 100, 0),
                    OonsiteemptiedDK = ifelse(onsite == 1 & WS13 == 8, 100, 0),
                    Oonsiteneveremptied = ifelse(onsite == 2 & WS12 == 4, 100, 0),
                    OonsiteDKemptied = ifelse(onsite == 2 & WS12 >= 8, 100, 0))



hh = hh %>% mutate(safedisposal = ifelse(septicemptiedpit == 100 | septicneveremptied == 100 | septicDKemptied == 100 | Oonsiteemptiedpit == 100 |
                                           Oonsiteneveremptied == 100 | OonsiteDKemptied == 100, 100, 0),
                   unsafedisposal = ifelse(septicemptiedHHpit == 100 | septicemptiedother == 100 | OonsiteemptiedHHpit == 100 |
                                             Oonsiteemptiedother == 100, 100, 0),
                   treatment = ifelse(septicemptiedproviderplant == 100 | septicemptiedproviderDK == 100 | septicemptiedDK == 100 | 
                                        Oonsiteemptiedproviderplant == 100 | OonsiteemptiedproviderDK == 100 | OonsiteemptiedDK == 100, 100, 0))



##########


hh = hh %>% mutate(connectedsewer = ifelse(WS11 == 11 | WS11 == 18, 100, 0),
                   usingimproved = ifelse(WS11 %in% c(14, 23, 41, 51, 96), 100, 0),
                   opendefecation = ifelse(WS11 == 95, 100, 0),
                   missingx = ifelse(WS11 > 97, 100, 0))




```





# WS 3.5

```{r}



hh <- read_sav(here("Data/Tunisia_hh.sav"))

source(here("R/drinkingWater.R"))

ch <- read_sav(here("Data/ch.sav"))


hh <- hh %>% left_join(ch, by = c("HH1", "HH2")) %>% filter(UF17 == 1, UB2 < 3)

hh = hh %>% mutate(stools = ifelse(CA31 %in% 1:2, 100, 0),
                   disposalplace = ifelse(CA31 == 98, 99, CA31))



```




# WS 3.6

```{r}


hh <- read_sav(here("Data/Tunisia_hh.sav"))
hh <- hh %>% filter(HH46 == 1) %>% 
  mutate(hhweightHH48 = HH48 * hhweight) %>% mutate(nhhmem = 1 * hhweightHH48)

var_lab(hh$nhhmem) = "Number of household members"; 
val_lab(hh$nhhmem) = make_labels("
1                        ")



source(here("R/drinkingWater.R"))




hh = hh %>% mutate(drinkingLayer = 0)

hh = hh %>% mutate(drinking = drinkingWater + 1) %>% 
  mutate(drinking = ifelse(WS1 %in% 11:12, 1,
                           ifelse(WS1 %in% c(61, 71) & WS4 <= 30, 1,
                                  ifelse(WS1 %in% c(13:14, 21, 31, 41, 51) & (WS3 %in% 1:2 | WS4 <= 30), 1,
                                         ifelse(WS1 %in% 91:92 & WS2 %in% 11:12, 1,
                                                ifelse(WS1 %in% 91:92 & (WS2 %in% c(61, 71) & WS4 <= 30), 1,
                                                       ifelse(WS1 %in% 91:92 & WS2 %in% c(13,14,21,31,41,51) & (WS3 %in% 1:2 | WS4 <= 30), 1,
                                                              ifelse(WS1 == 81, 4, drinking))))))))

var_lab(hh$drinking) = "Drinking Water"





hh = hh %>% mutate(sanitation = toiletType + 1) %>% 
  mutate(sanitation = ifelse(toiletType == 1 & sharedToilet == 0, 1, sanitation))

var_lab(hh$sanitation) = "Sanitation"

hh = hh %>% mutate(handwashing = 4) %>% 
  mutate(handwashing = ifelse(HW1 <= 3, 2,
                              ifelse(HW1 == 4, 3,
                                     ifelse(HW1 <= 4 & (HW2 == 1 & (HW7A == "A" | HW7B == "B")), 1, handwashing))))



hh = hh %>% mutate(basictotal = ifelse(drinking == 1 & sanitation == 1 & handwashing == 1, 100, 0))



```



# WS 4.1

```{r}


wm = read_sav(here("Data/Tunisia_wm.sav"))

names(wm) = sapply(names(wm), tolower)



##### end commonVarswm.sav


wm = wm %>% filter(wm17 == 1, !is.na(un16))


# wmweight - weight data

wm = wm %>% mutate(numWomen = 1 * wmweight) %>% 
  mutate(amaterialre = ifelse(un19 == 1, 100, 0),
         amaterialnonre = ifelse(un19 == 2, 100, 0),
         amaterialDKmissing = ifelse(un19 >= 8, 100, 0),
         materialother = ifelse(un18 == 2, 100, 0),
         materialDK = ifelse(un18 >=8, 100, 0),
         appropriatematerial = ifelse(un18 == 1, 100, 0),
         privateplace = ifelse(un17 == 1, 100, 0),
         totalprct = 100,
         materialprivateplace = ifelse(privateplace == 100 & un18 == 1, 100, 0),
         layer0 = 0, 
         layer1 = 0)




```





# WS 4.2

```{r}


wm = read_sav(here("Data/Tunisia_wm.sav"))


source(here("R/commonVarsWM.R"))

wm = wm %>% filter(wm17 == 1, !is.na(un16)) %>% mutate(numWomen = 1 * wmweight) %>% 
  mutate(noparticipation = ifelse(un16 == 1, 100, 0))






```


























